### PR TITLE
WIP: Py26compat

### PR DESCRIPTION
**Pull request by ericdill**
@campagnola How important is python 2.6 compatibility?  I started tackling this problem before I asked if you are planning on keeping python 2.6 support alive. I'll wait to hear back from you before I do any more work on this PR

### CODE REVIEW

**Comment by campagnola** [comment]
I'd certainly like to keep it alive a while longer--usually the people stuck on 2.6 are also the ones with very large install bases. That said, feel free to just open a general "fix 2.6" issue and move on if this turns out to be a lot of work.

**Comment by ericdill** [comment]
Great, thanks.  I'll keep hacking on this and see how far I get

**Comment by ericdill** [comment]
Well that sure is an unhelpful test name... https://travis-ci.org/ericdill/pyqtgraph/jobs/73963240#L697

**Comment by ericdill** [comment]
python 2.6 does not have `weakref.WeakSet`. In [test_stability.py] (https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/tests/test_stability.py#L37), you are using this.  There is a WeakSet backport available on pypi, so it could be included in the requirements or shipped with the project. What would you like to do here?

https://pypi.python.org/pypi/weakrefset

**Comment by campagnola** [comment]
In the past I have just used `WeakKeyDictionary` as a replacement for WeakSet. 
But on the other hand, I don't think test_stability needs to be 2.6 compatible--it doesn't contain any discoverable unit tests.

**Comment by campagnola** [comment]
@ericdill, what's the status on this? It looks like tests will pass once the WeakSet is removed. If you're busy, I can take it the last step..

**Comment by ericdill** [comment]
Ah thanks for circling back to this. Should I just get rid of `allWidgets` or turn it into a `WeakKeyDict` and modify the assignment on line 102?

**Comment by campagnola** [comment]
A `WeakKeyDictionary` would be best. Thanks!

**Comment by ericdill** [comment]
Alright, using a `WeakKeyDictionary`.  I'm using the widgets as the keys and using `1` as the value.  Seem sensible enough?

**Pull request merged**
