### PR TITLE
Check if Item actually has a parent before checking for collision

### PR DESCRIPTION
**Pull request by Dschoni**
Trying a fix for #884

### CODE REVIEW

**Comment by Dschoni** [comment]
If this works, would also close #511

**Comment by j9ac9k** [comment]
I think this PR may need to be rebased, some of the commits here appear unrelated.

As discussed in the issue, I'm reluctant to accept this fix as I'm not seeing how this case is possible to begin with and we may have another larger issue in play.

I want to walk through this test in the debugger and see if I can figure out why this is happening

**Comment by j9ac9k** [comment]
@Dschoni can you rebase this PR?

**Comment by Dschoni** [comment]
@j9ac9k My git is a mess right now. I did a rebase, leading me to an error ("Patch already has been applied"), so I had to merge remote tracking branch and.... well.... it should be kind of good now.

**Comment by j9ac9k** [comment]
> @j9ac9k My git is a mess right now. I did a rebase, leading me to an error ("Patch already has been applied"), so I had to merge remote tracking branch and.... well.... it should be kind of good now.

Ha, we've all been there with the git mess.  I'm going to close this PR, it's showing as having ~40+ commits with a bunch of file changes.

Checking for the parentItem() not being None I don't think is the way we want to solve this issue.  If we're going to do a check like this we should check if `self.scene() is None`; but I really do think this is a bug elsewhere in the `removeHandle` or `removeSegment` code.

**Pull request closed without merging**
