### PR TITLE
Remove all import *

### PR DESCRIPTION
**Pull request by Jaime02**
I have removed all the import * code, this makes all imports implicit.

### CODE REVIEW

**Comment by j9ac9k** [comment]
Hi @Jaime02 

Thanks for the PR.  The openGL related changes may need to be undone, those imports were very sensitive (hence the #noqa next to them).

**Comment by Jaime02** [comment]
@j9ac9k why? Is there a specific reason for importing all OpenGL stuff?

**Comment by j9ac9k** [comment]
> @j9ac9k why? Is there a specific reason for importing all OpenGL stuff?

Hi @Jaime02 

The import order is important here as some of the opengl functions/objects are intended to get clobbered/overwritten through the import sequence.  I learned this the hard way when I ran `isort` through the codebase and ran into a whole array of issues.

With the change you have proposed, the next time isort is run, all the opengl code will not work. 

While other maintainers may feel differently, I'm of the opinion that any import statement with `#noqa` should be left as they currently are.

**Comment by j9ac9k** [comment]
thanks @Jaime02 this LGTM, merging!

**Pull request merged**
