### PR TITLE
Fixes #3024

### LINKED ISSUE #3024: `PlotItem.scene()` has a `QGraphicsScene` type hint instead of a `pyqtgraph.GraphicsScene`
### Short description
`PlotItem.scene()` has a type hint of `QGraphicsScene | None` instead of a `pyqtgraph.GraphicsScene`. This raises an error when trying to access signals from the scene, such as `sigMouseMoved`.

### Code to reproduce
This is an abridged snippet of code from the `crosshair.py` example:

```python
import pyqtgraph as pg

def mouseMoved(evt):
    pass

p = pg.PlotItem()
p.scene().sigMouseMoved.connect(mouseMoved)
#         ^^^^^^^^^^^^^  Cannot access attribute "sigMouseMoved" for class "QGraphicsScene"
#                          Attribute "sigMouseMoved" is unknown
```

### Proposed Solution

I think this can be fixed by adding a type hint to the `GraphicsWidget` class:

```python
from typing import TYPE_CHECKING

class GraphicsWidget(GraphicsItem, QtWidges.QGraphicsWidget):
    # ...
    if TYPE_CHECKING:
        def scene(self) -> pyqtgraph.GraphicsScene: ...
```

If this seems reasonable, I can draft a PR.

### Tested environment(s)

* PyQtGraph version: 0.13.5 and 0.13.7
* Qt Python binding: PyQt6
* Python version: 3.12.2
* NumPy version: 1.26.4
* Operating system: Windows 10
* Installation method: Poetry

### PR DESCRIPTION
**Pull request by RushabhMehta2005**
Added type annotation to GraphicsWidget class.

Fixes #3024

### CODE REVIEW

**Comment by j9ac9k** [comment]
Thank you for the PR @RushabhMehta2005  Assuming CI passes, I'll merge this.

**Comment by RushabhMehta2005** [comment]
You're welcome! I'm new to open source and would love to contribute more. Can you provide some pointers / assign an issue to me ?

**Comment by j9ac9k** [comment]
> You're welcome! I'm new to open source and would love to contribute more. Can you provide some pointers / assign an issue to me ?

Nice! Congratulations on your merge!  Regarding issues, we have almost 400 open issues so take your pick 😅  

My recommendation would be, if you use the library, identify issues that effect you.  If you're new to development in general, I would avoid stuff that involves making changes to `ViewBox.py`

**Comment by RushabhMehta2005** [comment]
Thank you so much for your guidance! I will take my pick and see what issues I can solve.

**Pull request merged**
