### PR TITLE
PlotCurveItem OpenGL : avoid automatic conversion from float64 to float32

### PR DESCRIPTION
**Pull request by pijyoi**
There is an inefficiency in the current PlotCurveItem OpenGL implementation:
1) temporary float64 buffer created for vertices
2) tell PyOpenGL to use it as float32 (thus triggering a float64 - > float32 conversion) 

This PR changes step (1) to use a temporary float32 buffer right from the start.
This gains a few fps with 1,000,000 points: ```examples\PlotSpeedTest.py --opengl --frames 3 --nsamples 1000000```

Alternatively, if it is considered a bug that ```glVertexPointerf``` was used, then that should be changed instead to ```glVertexPointer(2, gl.GL_DOUBLE, 0, pos)```. However, this would then be a change in behavior to use double precision, and in addition, the calls to setting up the stencil should also be changed to double precision.

### CODE REVIEW

**Comment by j9ac9k** [comment]
Nice find @pijyoi 

I'm not sure what the consequences are of going to double-precision, so I'm inclined to think that we should probably maintain the single point precision given that's how it's been.

**Comment by NilsNemitz** [comment]
I can't help but feel that single-wide floats with a resolution of only around 1E-7 are a little weak for showing arbitrary data.

On the other hand, the placement of OpenGL in the library currently seems to be "fast at all costs", so sticking with single floats is probably justified. The viewing range and axis tick calculations would still work CPU-side, using doubles, I guess. So at least this should not require any special treatment of range limitations (like in the various breakages we get when zooming out too far).

How reliable is OpenGL support for double-wide float vertices? Are there platforms that we want to support where `glVertexPointer(2, gl.GL_DOUBLE, 0, pos)` is not available? That would certainly settle the question.

On a somewhat modern system, is there still a performance penalty for operation with double vertices?
I guess moving the data to graphics card memory will take twice as long...

**Comment by pijyoi** [comment]
>I can't help but feel that single-wide floats with a resolution of only around 1E-7 are a little weak for showing arbitrary data.

Yes, that's correct. #2020 has an example with artifacts when using OpenGL.

>On the other hand, the placement of OpenGL in the library currently seems to be "fast at all costs", so sticking with single floats is probably justified.

And also the OpenGL codepath has been untouched for ages. So not changing its behavior is the easiest course of action.

>How reliable is OpenGL support for double-wide float vertices? Are there platforms that we want to support where glVertexPointer(2, gl.GL_DOUBLE, 0, pos) is not available? That would certainly settle the question.

I remember reading language somewhere that an implementation is only needed to provide 24-bits of precision.

>On a somewhat modern system, is there still a performance penalty for operation with double vertices?
I guess moving the data to graphics card memory will take twice as long...

If you use CUDA with consumer graphics cards, there is a 32x performance penalty to using double precision versus single precision. So I would suspect that that would be true when using OpenGL too. Either that or the driver truncates it to float32 anyway, which still makes it compliant.

**Comment by NilsNemitz** [comment]
I'd say that is a fairly strong point for sticking to single-wide floats, then. There is a still a lot that can be done with 23 bits of mantissa.

Is there a good place to mention the single float limitation in the docs?

**Comment by j9ac9k** [comment]
32x performance penalty?!?!?! that's _brutal_ 

When I started reading more about cross-platform openGL code, I was coming across some articles (granted, they were ancient, like most openGL content) indicating that 64 bit float support within opengl drivers was fairly inconsistent... anyway that's a lot of reasons listed above to keep things as they are.

I am 👍🏻  on @NilsNemitz 's suggestion on adding a blurb in the docs about this limitation.

**Comment by pijyoi** [comment]
See the comments in the following link regarding double precision:
https://stackoverflow.com/questions/59740148/opengl-floating-point-precision

Basically, double precision is not used for processing even if the API allows you to provide double precision values.

**Comment by j9ac9k** [comment]
> See the comments in the following link regarding double precision: https://stackoverflow.com/questions/59740148/opengl-floating-point-precision
> 
> Basically, double precision is not used for processing even if the API allows you to provide double precision values.

I was just chatting with the [moderngl](https://github.com/moderngl/moderngl) maintainers and they explained more or less the same thing to me

**Comment by pijyoi** [comment]
>adding a blurb in the docs about this limitation.

Where would be a good place to put blurb? ```enableExperimental``` is effectively an undocumented option.

**Comment by j9ac9k** [comment]
I was thinking in the `useOpenGL` option here https://github.com/pyqtgraph/pyqtgraph/blob/master/doc/source/config_options.rst

Broadly speaking, and this is _way_ outside the scope of this PR, but we should likely add a separate section in the docs about benefits/consequences of enabling openGL for GraphicsView.

**Comment by j9ac9k** [comment]
Thanks @pijyoi !  I'm not an rst wizard, but can we get ordering/numbering to not be in-line in the rendered document?

https://pyqtgraph--2111.org.readthedocs.build/en/2111/config_options.html

**Comment by pijyoi** [comment]
would need some help here...

**Comment by j9ac9k** [comment]
I'll take a look I'm a bit; once I figure it out would you like me to push to your branch?

**Comment by pijyoi** [comment]
>once I figure it out would you like me to push to your branch?

Yes, please go ahead.

**Comment by j9ac9k** [comment]
welp, I got it, it's ugly as we run into a [known issue](https://github.com/readthedocs/sphinx_rtd_theme/issues/289) with the `sphinx_rtd_theme`

but the end result isn't offensive at least...

image

**Comment by j9ac9k** [comment]
@pijyoi since I requested the documentation bit, and it's added, I'm going to merge as soon as the CI comes back green.  Thanks for the PR!

**Comment by pijyoi** [comment]
Could you open a new issue on this?

**Pull request merged**
