### PR TITLE
Close windows at the end of test functions

### LINKED ISSUE #1040: Warnings output for visible windows after test functions run
When running the tests (I think as of merging #942), I get the following:

```
============================================================================================= warnings summary =============================================================================================
pyqtgraph/exporters/tests/test_svg.py::test_plotscene
pyqtgraph/graphicsItems/tests/test_AxisItem.py::test_AxisItem_stopAxisAtTick
pyqtgraph/graphicsItems/tests/test_ErrorBarItem.py::test_ErrorBarItem_defer_data
pyqtgraph/graphicsItems/tests/test_PlotCurveItem.py::test_PlotCurveItem
pyqtgraph/graphicsItems/tests/test_PlotDataItem.py::test_clipping
  /home/kenny/src/pyqtgraph/.venv-pyqt5/lib/python3.7/site-packages/_pytest/python.py:165: RuntimeWarning: Visible window deleted. To prevent this, store a reference to the window object.
    testfunction(**testargs)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================================================================= 50 passed, 5 skipped, 5 warnings in 9.77 seconds =============================================================================
Exception ignored in: <function GraphicsView._del at 0x7f8a7df8bc20>
Traceback (most recent call last):
  File "/home/kenny/src/pyqtgraph/pyqtgraph/widgets/GraphicsView.py", line 414, in _del
TypeError: 'NoneType' object is not callable
```

The `TypeError` is happening because `warnings.warn` is not available in some circumstances [[ref]](https://bugs.python.org/issue29174).

I think we just need to make sure any windows are closed at the end of the test functions so the warning isn't thrown during the tests. There aren't that many. The `TypeError` is kind of confusing so maybe we could catch that let it go in `GraphicsView._del` as well.

### PR DESCRIPTION
**Pull request by ixjlyons**
Fixes #1040

### CODE REVIEW

**Comment by j9ac9k** [comment]
LGTM

I'm on mobile so I can't see CI results easily, if they passed, I say go ahead and merge.

**Comment by ixjlyons** [comment]
Yep the warnings are gone. @2xB do you want to take a quick look at this? The `GraphicsView._del` function is getting pretty messy but I think we knew there'd be some corner cases to deal with.

**Comment by 2xB** [comment]
I think at this point we should really decide whether we want to keep the warning in `GraphicsView._del`. It is still an open question as written by @j9ac9k in https://github.com/pyqtgraph/pyqtgraph/issues/1021#issuecomment-522288478. Since this seems to have way more implications than expected and as far as I know there is nobody except from me really advocating this, it might be reasonable to just remove it.

Besides that, this PR looks good!

**Comment by ixjlyons** [comment]
Yep, I thought about that too. I'm generally in favor of the nicer warning and the problems we've run into so far aren't all that bad. The code *looks* a little ugly but it's not all that complicated at this point (especially compared to other stuff going on in pyqtgraph). I think we can keep moving forward and fixing things like this if/when they come up. With our testing to get 0.11 out and with users relying on the develop branch, I'm pretty sure we will or already have hit the edge cases.

**Comment by j9ac9k** [comment]
I'm not strongly opinionated one way or the other, but I agree with @ixjlyons that the code is a little ugly and for the time being we can patch things up as they arise.  Anyway, I'll merge this.

Thanks for the PR @ixjlyons

**Pull request merged**
