### PR TITLE
Implement PR313 Diff + Enable Infinite Line Example

### PR DESCRIPTION
**Pull request by j9ac9k**
This PR Implements PR 313 which cannot be merged due to coming from an `unknown repository` and there being a merge conflict.  Thank you to @lesauxvi for the PR, sorry it's taken us so long to follow up.

Fixes #313

### CODE REVIEW

**Comment by j9ac9k** [comment]
In slack chat @campagnola pointed out this feature is _really_ similar to [TargetItem](https://github.com/pyqtgraph/pyqtgraph/blob/f76fb3ac72281b942c632ea1198e84a2be55f4ae/pyqtgraph/graphicsItems/TargetItem.py).  I think this PR should be modified to incorporate its features into the TargetItem object instead of creating a separate one

**Comment by j9ac9k** [comment]
CursorItem is far more feature complete than TargetItem, ....going to collect some feedback from others, but I'm considering renaming CursorItem to TargetItem; and overwriting the current implementation.

**Comment by ixjlyons** [comment]
> I'm considering renaming CursorItem to TargetItem; and overwriting the current implementation

Sounds good to me :+1:

Should `CursorItem` be made more visually compatible with `TargetItem` in that case (i.e. the crosshairs)? It makes it a little more distinct from an ROI and gives a more precise indication of the center.

**Comment by j9ac9k** [comment]
Started merging the CursorItem into the existing TargetItem, while supporting the array of existing Symbols as potential entries.... hover pen isn't working, and neither is click + drag...more investigation needed.

**Comment by j9ac9k** [comment]
Went for a different way, closing this PR

**Pull request closed without merging**
