### PR TITLE
Convert == None checks to is None

### PR DESCRIPTION
**Pull request by ksunden**

### CODE REVIEW

**Comment by j9ac9k** [comment]
There are a few places in the repo we have `!= None` which would probably be appropriate to grab.

I see two instances in `ROI.py`, `ParameterItem.py` (granted that one is part of a string in an exception) and `test_dock.py`

**Comment by ksunden** [comment]
The ROI ones were addressed by #2095

**Comment by ksunden** [comment]
I do not care about the exception one, I think its current state is readable and gets the point across, and if anything changing it would be _less_ readable in this case.

**Comment by j9ac9k** [comment]
That's legit, LGTM, another PR can capture the `==/!= True/False` bits   Merging this, thanks @ksunden !

**Pull request merged**
