### PR TITLE
Skip some test examples

### PR DESCRIPTION
**Pull request by j9ac9k**
This PR skips two tests

1. The remote plotting test is skipped, this is failing pretty consistently, and will likely take a fair amount of work/investigation to diagnose.
2. `optics_demo.py` is skipped when running with pyside1, this is due to a known bug that is even linked as a comment in the code.

### CODE REVIEW

**Comment by j9ac9k** [comment]
Huh, for some reason `optics_demos.py` was not being skipped, do not merge until this is resolved.

**Comment by j9ac9k** [comment]
had the skip logic backwards, I think this is ready for merging, but will leave up for anyone else to comment

also how about that, 5 successful checks!

**Comment by j9ac9k** [comment]
I'm on the fence here, I hate skipping `RemoteSpeedTest.py`"because it's always failing" but I have no knowledge of multiprocessing code to to try and address it.

Also, should we not be making use of `QThread` for any kind of multithreading as it is, and thus consider deprecating `RemoteSpeedTest.py`?

Pinging @2xB @ixjlyons and @campagnola for thoughts (anyone else should feel free to chime in as well).

**Comment by 2xB** [comment]
I'd suggest to skip it for now but to keep issue #881 open containing the remark that it is now skipped but one can access old logs like https://dev.azure.com/pyqtgraph/pyqtgraph/_build/results?buildId=168&view=logs to see it. This does not seem like a central feature of pyqtgraph, and having a succeeding CI pipeline on `develop` is very helpful. Nevertheless it should at some point be tackled.

For the `QThread` suggestion, I think the point with this example is to show that one is able to generate data and plot in two different processes with different namespaces, not only threads - Probably the idea was to demonstrate that one could have one application generating data and sending it asynchronously to a pyqtgraph application?

**Comment by j9ac9k** [comment]
I'll preface by saying I really don't understand the multiprocessing code within pyqtgraph so I could be way off base, but doesn't `QThread` effectively create a new namespace as well, where the only way of getting data across the threads is using signals?

I'll merge this for now, as @campagnola has suggested we skip this test due to its consistent failures, and I think leaving #881 open is the right call but we _should_ get this example working.

**Pull request merged**
