### PR TITLE
use qWaitForWindowExposed instead of qWaitForWindowShown

### PR DESCRIPTION
**Pull request by pijyoi**
qWaitForWindowShown has been obsolete since Qt 5.6

In view of the comments in #1533  and #1535, the shim is left behind for Qt5 but removed for Qt6.
However, can this particular shim really be considered part of pyqtgraph's public API given that it is only used in pyqtgraph's unit tests?

### CODE REVIEW

**Comment by j9ac9k** [comment]
I think we're good killing this off altogether, appreciate the concern given the feedback; doing a quick search on github for `pyqtgraph.QtTest` and `pg.QtTest` yields no results.

I'm not strongly opinionated on this, but if we did decide to deprecate it, we should try and emit a deprecation warning when someone would access that module.

**Comment by pijyoi** [comment]
The problem with monkey patching the module directly:
```
>>> import pyqtgraph
>>> from PySide2 import QtTest
>>> QtTest.QTest.qWaitForWindowShown
<built-in method qWaitForWindowExposed of Shiboken.ObjectType object at 0x00000205FF74A4A8>
```
This is how #1533 affected biolab/orange3.

**Comment by j9ac9k** [comment]
If we can't put a deprecation notice on this..I'm good with killing this off.

**Comment by j9ac9k** [comment]
LGTM, thanks @pijyoi

**Pull request merged**
