### PR TITLE
Control si prefix

### PR DESCRIPTION
**Pull request by eisoku9618**
I would like to switch enableAutoSIPrefix to False by setLabel argument.

### CODE REVIEW

**Comment by eisoku9618** [comment]
passed travis.
How about this PR?

**Comment by ericdill** [comment]
Can you add a docstring entry for the new `enableAutoSIPrefix` kwarg in both `setLabel` functions?

**Comment by ericdill** [comment]
other than that, LGTM

**Comment by eisoku9618** [comment]
Thank your for reviewing, I've added the docstring.

**Comment by eisoku9618** [comment]
passed Travis!

**Comment by campagnola** [comment]
Can you give an example of where this will be useful? To disable si-prefixing, I just write the unit string directly into the label text, like:

    axis.setLabel('X axis (units)')

Since the `units` argument is not specified, no si-prefix will be added.

**Comment by eisoku9618** [comment]
Indeed, ’’axis.setLabel('X axis (units)')’’ can disable auto si prefix and I use a similar code in other python graphics packages like matplotlib.

But, pyqtgraph has an interface to set unit **explicitly** while matplotlib does not, and I liked that.
I think spliting label text and unit improves readability, so I prefer to use units argument.

**Comment by campagnola** [comment]
Hm.. I am not convinced. I prefer the API to be as simple as possible, and the `units` argument only exists to allow automatic SI prefixing, not to improve readability.

This issue follows in a long series of feature requests around text formatting, and I am actually considering going the opposite direction--instead of the `units` argument, let the user specify exactly how the label should be formatted like `setLabel("X Axis ({sipfx}Units)")`.

**Comment by eisoku9618** [comment]
OK, I will use ``axis.setLabel('X axis (units)')`` style. Thank you for your reviews!

**Pull request closed without merging**
