### PR TITLE
PlotItem.addItem checks item's existence

### PR DESCRIPTION
**Pull request by xiaoqiangwang**
It should avoid adding an item twice.

### CODE REVIEW

**Comment by lesauxvi** [comment]
That seems ok for me. What do you think @campagnola  and @ericdill ?

**Comment by lesauxvi** [comment]
ping @campagnola and @ericdill

**Comment by 2xB** [comment]
Looks good to me. As in any case I can imagine adding a PlotItem twice is not intended, I'd suggest to also raise a RuntimeWarning stating that an item was added twice to help debugging.

**Comment by j9ac9k** [comment]
I attempted to make the changes on this PR but couldn't (got a permission denied error).  

@xiaoqiangwang thanks for the PR, sorry it's taken us so long to get to this.  I'm implementing this change along w/ the suggested change from @2xB in #1239

**Pull request closed without merging**
