### PR TITLE
Fix Regression in in ViewBox.updateScaleBox Caused by #2034

### PR DESCRIPTION
**Pull request by campagnola**
PR #2034 was merged to fix issue #1937. However, #1937 was _also_ fixed by #2057, while #2034 created the new issue #2237. (are you still with me?)

So this PR just reverts #2034, hopefully resulting in a state that fixes both #1937 and #2237. 

I'm not totally sure I tracked everything correctly here, so I'd appreciate a confirmation from someone else..

### CODE REVIEW

**Comment by j9ac9k** [comment]
Just going to tag @swvanbuuren to thank them for their fantastic MWE in #1937 which I just used to test this PR, which works for me.

I also want to thank @leo603222 for authoring #2034, even thought we are reverting it now, it fixed a critical issue in part of the code that isn't so easy to understand.

This LGTM @campagnola

**Comment by j9ac9k** [comment]
@campagnola I'm going to edit the title of your PR as it's used in the automatic changelog generation by github, hope you don't mind!

**Comment by markotoplak** [comment]
I tried this PR with visualizations in Orange. With pyqtgraph-0.12.3 I was able to easily replicate #1937 and with the current release #2237. On this branch, I can not replicate either, so at least for my use case, everything seems fine. Thanks!

**Comment by j9ac9k** [comment]
Thanks you so much for testing this @markotoplak I'm going to merge this, and likely do a pyqtgraph release shortly (trying to see what other PRs are close to ready for merging and we want to sneak them in).

**Pull request merged**
