### PR TITLE
Create set axis invert

### PR DESCRIPTION
**Pull request by hyperiongeo**
As mentioned previously, created a setAxisInvert function. Also add to example for testing.
Slight change to the the addAxis to align with underlying AxisItem

### CODE REVIEW

**Comment by NilsNemitz** [comment]
Hi @hyperiongeo !
This seems to be based on the experimental Multi-axes code now.
Do you think you can change that to be based on the regular master branch?

**Comment by hyperiongeo** [comment]
Okay, I think that worked to update the commit.

**Comment by j9ac9k** [comment]
Hi @hyperiongeo 

There is a bit of an issue, this PR aims merge your proposed changes (that's fine) but also seeks to include PR 1359 which is not ready for merging.

I've been bouncing around between PRs so I'm a bit disoriented so forgive me if you've already explained where your proposed changes should go.

If the 2 commits you added are intended to be part of PR 1359, what you need to do is edit this PR so that the target branch of this PR is not `pyqtgraph/master` but `0000matteo0000/master`.  This way, 0000matteo0000 would get the PR notification and he can decide to incorporate your commits into his branch (and thus his PR) or not.

If you intended for your code changes to be merged into pyqtgraph, completely independent of 1359, then you're going to have a bit more work to do.... 

```bash
git switch master  # change to the master branch
git pull upstream master  # sync up your local copy of the master branch w/ the upstream
git switch -c create_setAxisInvert_staging  # create a new branch from the current master branch
git cherry-pick 902fe9b4b79f82dfa8bfce76c810f9b37bf354c0~.. 53d3c6995acfdbea86552d21ef7dc6208c524d63  #grab just the commits for the files you changed
git switch create_setAxisInvert  # go back to the branch this PR is based off of
git reset --hard create_setAxisInvert_staging  # make that branch be like the staging branch
git push --force-with-lease # push the changes to your remote git repo, overwriting the history on the remote branch
```

Haven't actually tested this, just typed this out from memory.

Hope that helps!

**Comment by hyperiongeo** [comment]
@j9ac9k Sorry for the confusion.  I think the easiest is to close this PR and resubmit with the recommended setup.  Thanks

**Comment by j9ac9k** [comment]
No problem, feel free to reach out on discord or wherever if I can be of help!

**Pull request closed without merging**
