### PR TITLE
Fixing the border rect overlapping for ViewBox and GraphicsLayout

### PR DESCRIPTION
**Pull request by espdev**
This PR fixes issue #316 
Please review this PR.

### CODE REVIEW

**Comment by half-adder** [comment]
Any news on this?

**Comment by j9ac9k** [comment]
I'm not opposed to merging this (especially as @campagnola was involved with the referenced issue) . This is a tough thing to evaluate due to changes to ViewBox which we consider to be really fragile.  

Also our priorities are right now with getting our test suite to pass.  To move this up our queue some steps that would be good to add are

1. Resolve the conflicts with `ViewBox.py`
1. Re-run against our CI suite (something we can manage after the conflicts are handled).
2. Add a test that fails for the current implementation, but passes  with the fix.

**Comment by espdev** [comment]
I'm sorry. I was working on it 3 years ago and did not get any feedback. Now I don’t remember the implementation details. If someone completes this work, I will be more than happy.

**Comment by j9ac9k** [comment]
@espdev Thanks for the PR, nobody is expecting you to update this from 3 years ago.  This PR does address an issue with the library that we would like to have fixed.  I can see some of the other collaborators (or myself) picking this up and going with it; I was merely relaying to @half-adder where our current priorities were lying and laying out what it would take to get this merged right away.

**Comment by espdev** [comment]
I have resolved conflicts but I cannot guarantee the code works correctly. :)
I will try to check it soon.

**Comment by j9ac9k** [comment]
> I have resolved conflicts but I cannot guarantee the code works correctly. :)
> I will try to check it soon.

Thanks so much for both the original PR and the follow up/update.  If there is a specific use case you're concerned about, but can't get to it, let me know and I'll try and dive into it.

**Comment by espdev** [comment]
I have checked this changes on my example from the issue. It seems to me it works.

`develop` branch (78df356c):


`fix-issue316` branch (1955ae0):


What additional automatic tests can we add?

**Comment by j9ac9k** [comment]
I'm not sure what tests can be added honestly, but this is looking pretty good, I was hoping to merge this last night but we had a miniconda 4.7.x issue in our CI that caused all sorts of havoc.  I'll try and get to this today.

**Comment by j9ac9k** [comment]
This looks good to me, I'm going to merge.  Thanks again for the PR, I'm sorry it took us so long to follow up with you.

**Pull request merged**
