### PR TITLE
AxisItem: Account for empty strings in the visibility of text and units

### PR DESCRIPTION
**Pull request by dgoeries**
- Account for empty `text` and `units`
- Always reset the visibility of the label, in case of swap

### CODE REVIEW

**Comment by j9ac9k** [comment]
Changed the base, I really should update the `CONTRIBUTING.md` instructions...

**Comment by dgoeries** [comment]
Thanks! I believe I have to look at the tests. An exporter is failing now ...

**Comment by dgoeries** [comment]
All tests pass through now. I had to cleanup a bit the AxisItem and disentangle the `setLabel` from internal use. There is way more potential for separation and cleanup.

There might be a slight regression potential depending on how the method was used. I put this to expected behavior (at least for me, `None` means empty label.)

Can you have a look again please.

**Comment by j9ac9k** [comment]
Thanks for the PR @dgoeries , sorry this took me so long to get to; these diffs look good to me, but given I already hosed up AxisItem once by merging quickly, I'll ask @ixjlyons or @ksunden to take a look.

**Comment by j9ac9k** [comment]
After taking another look, I think this is good, thanks again for the PR @dgoeries merging!

**Pull request merged**
