### PR TITLE
Adding setter for GLGridItem.color

### PR DESCRIPTION
**Pull request by 2xB**
`GLGridItem` has a color attribute that has no setter. This Pull Requests adds such a setter function. It originates from a cherry-picked commit from PR #419.

### CODE REVIEW

**Comment by 2xB** [comment]
It can e.g. be tested running the `GLMeshItem` example interactively and executing `g.setColor((1,1,0,1))`.

**Comment by 2xB** [comment]
PR #397 aims at providing the same function. Differences are: 
* That PR function accepts everything `QColor()` also accepts, this PR function accepts an `(r,g,b,a)` tuple. PR #397 does not accept the tuples currently only accepted by `GLGridItem`, so this would change the API.
* That PR is missing a call to `self.update`.
If desired, I can add a call to QColor if no tuple is given.

**Comment by ixjlyons** [comment]
I wrote a few notes recently about this here: https://github.com/pyqtgraph/pyqtgraph/issues/283#issuecomment-507730765

I'm not sure how consistent the rest of the code is, but I think it makes sense to "hide" the color attribute as `self._color` when there's an explicit getter/setter.

**Comment by 2xB** [comment]
Thank you, the last two commits made `GLGridItem` consistent with `GLBoxItem`. That includes making the `color` attribute private, adding a getter and using `pyqtgraph.function.Color` to parse the color arguments with a corresponding docstring similar to that one in GLGridItem.

**Comment by j9ac9k** [comment]
@2xB  thanks for the PR.  I'm good with merging this; when merging this does this mean we can close #397 and #419 ?

**Comment by 2xB** [comment]
Yes, this PR contains the part of #419 that still applies, and has the same goal as #397, although a slightly different approach (a comparison is done in a comment further above).

**Comment by 2xB** [comment]
Btw. I created this PR as an updated version of #419, which is why I already closed #419 when creating this PR. In retrospect, I am not sure if that was a wise decision.

**Comment by j9ac9k** [comment]
Closing/Opening to trigger new CI run.

**Pull request merged**
