### PR TITLE
Use Python 3.9 to Test CI on [Latest] Versions

### PR DESCRIPTION
**Pull request by j9ac9k**
As Python 3.9 is out, we should likely test that on our CI platform... Only the latest versions of PyQt5/PySide2 are tested against Python 3.9.

### CODE REVIEW

**Comment by j9ac9k** [comment]
umm....azure?

**Comment by j9ac9k** [comment]
🤦‍♂️  step one, maybe check if numpy has released a python 3.9 version yet (narrator: they have not).

**Comment by j9ac9k** [comment]
Also there is no windows 3.9 available on any of the azure hosted agents; 

https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

**Comment by j9ac9k** [comment]
Windows 3.9 is now available on all the "agents" we use on azure, but numpy doesn't have a python 3.9 release yet ...

**Comment by j9ac9k** [comment]
Numpy with python 3.9 support has been released, but no scipy yet...

**Comment by j9ac9k** [comment]
New scipy now released, I think we're ready to try again...

**Comment by j9ac9k** [comment]
Now having issues w/ `test_reload` on pyside2 5.15.1

**Comment by highfestiva** [comment]
Verified the basics are working, found an incompatibility between this version and the previous (which are unrelated to this commit):

````python
ax.axes['left']['item'].textWidth = 65 # no longer sets the margin
````

Will start looking at pyside and `test_reload` when I get some time off.

**Comment by highfestiva** [comment]
It has to do with the `gc.get_referrers()` not fetching all referrers when PySide2 is loaded. Have no idea why. Working version:

````
Reloading <module 'reload_test_mod' from 'C:\\Users\\jonte\\AppData\\Local\\Temp\\tmpmh04ap8z\\reload_test_mod.py'>
  Updating class reload_test_mod.C (0x280785595a0 -> 0x28078567660)
    Ignoring reference <class 'dict'>
    Changed class for <reload_test_mod.C object at 0x00000280793D0CA0>
    Ignoring reference <class 'tuple'>
    Ignoring reference <class 'tuple'>
````

When PySide2 is loaded:

````
Reloading <module 'reload_test_mod' from 'C:\\Users\\jonte\\AppData\\Local\\Temp\\tmpu0xx6_rc\\reload_test_mod.py'>
  Updating class reload_test_mod.C (0x2112ec3a6c0 -> 0x2112ec3aad0)
    Ignoring reference <class 'dict'>
    Ignoring reference <class 'tuple'>
    Ignoring reference <class 'tuple'>
````

**Comment by highfestiva** [comment]
The minimal test to reproduce the bug:

````python3
import gc

def test_pyside2_referrers(): # fails
    from PySide2.QtCore import QObject
    o = QObject()
    assert len([ref for ref in gc.get_referrers(QObject) if isinstance(ref, QObject)]) == 1

def test_pyqt5_referrers(): # works
    from PyQt5.QtCore import QObject
    o = QObject()
    assert len([ref for ref in gc.get_referrers(QObject) if isinstance(ref, QObject)]) == 1
````

PySide2's class is of type `Shiboken.ObjectType`. I'm not able to get much from [this](https://pyside.github.io/docs/shiboken/ownership.html). Sorry I couldn't be of more help!

**Comment by highfestiva** [comment]
Does this mean the release will be postponed further, or can this feature be scrapped? (It's unclear to me what a reload function has to do with plotting graphs in Qt.)

**Comment by highfestiva** [comment]
@j9ac9k ping?

**Comment by j9ac9k** [comment]
There are a few other PRs that are just about ready for merging; I'd like to get a little further along w/ them. 

If you need to install the current build of the master branch you can always install it from the git repo directly

```
pip install git+https://github.com/pyqtgraph/pyqtgraph.git
```

Please keep in mind maintainers here are volunteers that have other professional and personal responsibilities that often takes precedence over our open source work.  I love the idea of frequent releases; but when I do get time to work on pyqtgraph, my first priority is to address regression bugs, followed by resolving outstanding PRs.  The further we get along there, the sooner we can deprecate Py2, Py3 < 3.7, Qt4, Qt5 < 5.12, which will make future development/testing/releases far easier.  We used to have ~170 open PRs, currently we are at 35.

**Comment by j9ac9k** [comment]
Superseded by #1474

**Pull request closed without merging**
