### PR TITLE
Fix set empty

### PR DESCRIPTION
**Pull request by NilsNemitz**
Proposed fix for issue #1445 

The direct reason of the crash when setting plot data to [],[] was that dataRect assumes empty data will appear as None.
--> Added sanity check to avoid crash.

I checked why the user would set data to [], [] and found that this seems necessary to actually delete the plot on-screen.
I think this is unintended behavior:
Setting yData to None triggers a shortcut that fails to invalidata _dataRect and xClean / yClean. In my tests that seemed to prevent the graph actually getting deleted from screen.
--> removed shortcut

Calling setData() seems to try and set xData and yData to None. But then None gets sanitized to np.array(None), which is unfortunately not actually None.
--> special-cased the code to allow xData and yData to be set to None

Data can now be cleared by calling setData(). But existing code probably calls setData( [], [] ). 
--> zero-length datasets now convert to xData = None and yData = None.

While looking at the code, I found that any data passed as named parameters 'x' and 'y' never gets sanitized
--> added forced conversion of MetaArray to ndarray as used elsewhere.

I hope one of the developers can comment  :)
On my system the modified code seems to give the intended behavior without crashing any of the examples I tested.

### CODE REVIEW

**Comment by j9ac9k** [comment]
Hey @NilsNemitz thanks for the super-fast PR, I haven't finished drinking my coffee this morning.  

Would you  mind updating `test_PlotDataItem.py` with `test_setData()` having another example of `pdi.setData([], [])`?

**Comment by NilsNemitz** [comment]
Dear @j9ac9k, it is the other end of the world here and very late. I will look into it tomorrow.

**Comment by j9ac9k** [comment]
> Dear @j9ac9k, it is the other end of the world here and very late. I will look into it tomorrow.

Haha, sure thing!  thanks again for jumping on this.

**Comment by NilsNemitz** [comment]
Hi @j9ac9k , I have added the tests. 

pdi.setData()
--> assert xData and yData is None

pdi.setData( [],[] )
--> assert xData and yData is None

Fascinatingly, 
np.array(None) == None  --> True
np.array(None) is None --> False
Neat textbook case... I hope these won't happen anymore.

I found that there is a PlotDataItem.clear() command that was probably the intended way to clear the data.
The test for this asserted xData == None.
--> changed the assertion for pdi.clear() to "xData is None".

While checking that setData() and clear() both invalidate cached data properly, I found that xClean and yClean are never used in the entire pyqtgraph code folder, except when they get set to None.
--> Commented out all remaining references. It seems they have been added ~7 years ago, so I guess they can be removed?

Tests pass on my system with PyQt5, except for the GL stuff that I probably haven't set up correctly.

**Comment by 2xB** [comment]
@NilsNemitz Thank you! Regarding `xClean` and `yClean`: Yes, I'd not comment things out but remove them entirely. Since these properties are not documented and not used, I'd assume it is safe to remove them, and if this PR is found to prove an issue later, one can always look at the old code in the old Git commits.

**Comment by NilsNemitz** [comment]
@2xB , thank you for the clear instructions, all remains of xClean and yClean are gone now.
Any advice on the failed test? I can only find this:
`pyqtgraph/tests/test_exit_crash.py::test_pg_exit `
`[gw0] [ 85%] FAILED pyqtgraph/tests/test_exit_crash.py::test_pg_exit`
...and I fail to see how that may be related to anything I touched.

**Comment by j9ac9k** [comment]
That test is flaky, should pass on rerun which I'll trigger on a bit.

**Comment by j9ac9k** [comment]
This LGTM, thanks for the PR @NilsNemitz

**Pull request merged**
