### PR TITLE
WIP: Testing codecov and coveralls

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by ericdill** [comment]
This will probably work. My experience with codecov/coveralls is that I tweak .Travis.yml on master a few times and it starts working eventually. I'll be happy if this makes codecov start working, but I will not be surprised if it needs more tweaking

**Comment by campagnola** [comment]
Well.. 
https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/73616000#L1046

**Comment by campagnola** [comment]
probably due to the `cd /` in the preceding command.

**Comment by ericdill** [comment]
Another good catch @campagnola !  Updated travis.yml and it is uploading correctly

https://codecov.io/github/pyqtgraph/pyqtgraph?ref=5ba3e7b6ddc414bff76757f4ea0d6e915ee2afe7

**Comment by campagnola** [comment]
Ooohh that coverage report stings.

**Comment by ericdill** [comment]
Yeah, but it's a place to start!

**Comment by ericdill** [comment]
Now that travis and coveralls/coverage seem to be working, the travis builds can be restarted with the little circular arrow on the right side of the page

looks like --> ![screen shot 2015-08-01 at 9 37 27 pm]
(https://cloud.githubusercontent.com/assets/6223243/9024309/e418af66-3896-11e5-85e8-cd4bd9f32ee9.png)

**Comment by ericdill** [comment]
I'd restart the builds but I can't do it because you need commit rights to do it

**Pull request merged**
