### PR TITLE
feature TriangleROI

### PR DESCRIPTION
**Pull request by feketeimre**
Added equilateral  TriangleROI.
getArrayRegion is not working yet

### CODE REVIEW

**Comment by j9ac9k** [comment]
Closing/Re-Opening to trigger new CI run

**Comment by j9ac9k** [comment]
always forgetting to change the base/target branch...

**Review by outofculture — CHANGES_REQUESTED** [review]
This is a nice idea, and nearly ready for merging. Inline comments describe changes needed. Also, an example should be added to `examples/ROIExamples.py`.

**Comment by outofculture** [comment]
This PR has been superseded by #1581. Thank you @feketeimre for the new feature!

**Pull request closed without merging**
