### PR TITLE
Update LegendItem.py

### PR DESCRIPTION
**Pull request by kevinanewman**
Propose adding a clear() method (or equivalent) for easier legend re-use with dynamically updated plots...

### CODE REVIEW

**Comment by 2xB** [comment]
@kevinanewman With the `pyqtgraph 0.11.0` version (as currently on branch `develop`), items removed from a plot will also be removed from the legend so if a plot is cleared, its legend is also cleared. Does this solve the problem you address with this Pull Request?

**Comment by sharon92** [comment]
clear() method works well on 0.11.0

But it would also be nice to update legends by setting name in setData.

for eg. 

`PlotDataItem.setData(x=X,y=Y, name = 'New Name')`

**Comment by 2xB** [comment]
@sharon92 This should work, yes. Might you please open an issue regarding this?

**Comment by sharon92** [comment]
@2xB Done!

**Comment by kevinanewman** [comment]
In regards to 

> @kevinanewman With the `pyqtgraph 0.11.0` version (as currently on branch `develop`), items removed from a plot will also be removed from the legend so if a plot is cleared, its legend is also cleared. Does this solve the problem you address with this Pull Request?

The way my code works right now is that I create the chart and the curves and then dynamically update them... I'm trying to reuse all the chart elements and just set new data.  So, I'm not removing the curves, I just give them new data.  I needed a way to clear the legend so that I could create new labels for the new curves.

Maybe there's a better way to do this, I'm open to suggestions, otherwise it's working well for my live simulation outputs.

Thank you,
Kevin

**Comment by j9ac9k** [comment]
@kevinanewman thanks for the PR, sorry it's taken us a while to review it.  Change looks good to me, i'll be merging shortly.

**Pull request merged**
