### PR TITLE
Fix GL Views being half size on hidpi monitors

### LINKED ISSUE #497: Retina display 3D issue
When opening a 3D example on a Mac with a Retina (HiDPI) display, the scene is only rendered in the bottom left quadrant of the window.

screen shot 2017-06-09 at 10 19 47 am

Anaconda environment includes:

numpy                     1.11.3                   py35_0  
pyopengl                  3.1.1a1             np111py35_0  
pyqt                      5.6.0                    py35_1  
pyqtgraph                 0.10.0+gaf4c673           <pip>
scipy                     0.19.0              np111py35_0

### PR DESCRIPTION
**Pull request by mshunshin**
On retina / hidpi displays GL Views are too small.

I have modified the appropriate self.width and self.height to multiply by self.devicePixelRatio.

I.e.:
`
(0, 0, self.width(), self.height())`

becomes

`(0, 0, self.width()*self.devicePixelRatio(), self.height()*self.devicePixelRatio())`

Fixes #497  and #422 

Needs checking on a non-retina non-mac device first.

### CODE REVIEW

**Comment by RobbieClarken** [comment]
This PR fixes the issue for me on a Retina MBP with PyQt 5.9. I've also tested on a low resolution Windows laptop and it works fine there too.

**Comment by hoatd** [comment]
It works for me on my MBP (Retina, 13-inch, Early 2015), macOS High Sierra 10.13, default Python 2.7.10, PyQt 5.9_1 (brew).
Thank you very much!

**Comment by campagnola** [comment]
Thanks @mshunshin!

**Comment by lericson** [comment]
I'm not sure you've properly tested these changes, for reference, here is what I had to change to regain sane behavior:

```
            return (0, 0, self.devicePixelRatio()*self.width(), self.devicePixelRatio()*self.height())
            region = (0, 0, self.devicePixelRatio()*self.width(), self.devicePixelRatio()*self.height())
        region = (region[0], self.devicePixelRatio()*self.height()-(region[1]+region[3]), region[2], region[3])
        return xDist / self.devicePixelRatio()*self.width()
        w = self.devicePixelRatio()*self.width()
        h = self.devicePixelRatio()*self.height()
~/devel/pysquad git:master % grep -iC5 devicepixel squad/trajview.py
        self.update()

    def getViewport(self):
        vp = self.opts['viewport']
        if vp is None:
            return (0, 0, self.devicePixelRatio()*self.width(), self.devicePixelRatio()*self.height())
        else:
            return vp

    def setProjection(self, region=None):
        m = self.projectionMatrix(region)
--
        glMultMatrixf(a.transpose())

    def projectionMatrix(self, region=None):
        # Xw = (Xnd + 1) * width/2 + X
        if region is None:
            region = (0, 0, self.devicePixelRatio()*self.width(), self.devicePixelRatio()*self.height())

        x0, y0, w, h = self.getViewport()
        dist = self.opts['distance']
        fov = self.opts['fov']
        nearClip = dist * 0.001
--
    def itemsAt(self, region=None):
        """
        Return a list of the items displayed in the region (x, y, w, h)
        relative to the widget.
        """
        region = (region[0], self.devicePixelRatio()*self.height()-(region[1]+region[3]), region[2], region[3])

        #buf = np.zeros(100000, dtype=np.uint)
        buf = glSelectBuffer(100000)
        try:
            glRenderMode(GL_SELECT)
--
            cam = np.array(cam).reshape((1,)*(pos.ndim-1)+(3,))
            dist = ((pos-cam)**2).sum(axis=-1)**0.5
        else:
            dist = (pos-cam).length()
        xDist = dist * 2. * np.tan(0.5 * self.opts['fov'] * np.pi / 180.)
        return xDist / self.devicePixelRatio()*self.width()

    def mousePressEvent(self, ev):
        self.mousePos = ev.pos()

    def mouseMoveEvent(self, ev):
--

    def readQImage(self):
        """
        Read the current buffer pixels out as a QImage.
        """
        w = self.devicePixelRatio()*self.width()
        h = self.devicePixelRatio()*self.height()
        self.repaint()
        pixels = np.empty((h, w, 4), dtype=np.ubyte)
        pixels[:] = 128
        pixels[...,0] = 50
        pixels[...,3] = 255
```

**Pull request merged**
