### PR TITLE
[wip] Imageitem performance

### LINKED ISSUE #667: ndarray.dtype check fails erroneously leading to performance degradation
https://github.com/pyqtgraph/pyqtgraph/blob/b421cc27905338438e99cf19d4962c51e64079bd/pyqtgraph/functions.py#L1115

It looks like, ndarray.dtype cant be checked using "is" or "is not", it should be compared using == operator: 

In [1]: import numpy as np

In [2]: np.array([1,2], dtype=np.ubyte)
Out[2]: array([1, 2], dtype=uint8)

In [3]: x = _

In [4]: x.dtype
Out[4]: dtype('uint8')

In [5]: x.dtype is not np.ubyte
Out[5]: True

In [6]: x.dtype == np.ubyte
Out[6]: True

### PR DESCRIPTION
**Pull request by campagnola**
Working on improving update performance of ImageItem:
* ensure that ubyte data can be passed through to QPixmap without any extra overhead
* optimize levels / lookup tables / clipping / channel ordering where possible (maybe we can use numba to combine multiple steps into a single loop)

Fixes #667

### CODE REVIEW

**Comment by j9ac9k** [comment]
This PR was still pointing to `develop`, not `master`... hey look at that, it's no longer 200+ commits in a PR :D

**Comment by joshdoe** [comment]
I tested out this PR in my app, and for a 4k30hz video the display framerate goes from 2.5Hz up to 14Hz, quite an improvement.

**Comment by j9ac9k** [comment]
Closing/Opening to trigger run in new CI

**Comment by outofculture** [comment]
Okay, so considering #1466 is about to get merged, I dug in and figured out what other improvements are in this branch. The primary optimization here was pre-allocating the processing buffer, which is included as part of #1466. This branch does fix a bug (#667), improves docstrings, profiler and code clarity in a few places, and adds an Air-Speed-Velocity-based benchmark tool. These two branches have conflicting changes, so I made [a new branch](https://github.com/outofculture/pyqtgraph/tree/pr-669-merged) with those ironed out, and a few other things cleaned up. The hopeful list at the beginning of this PR is, as yet, undone, so I'm going to recommend we close this PR for now and make a new one out of the merged branches that better describes its functional intent.

**Comment by j9ac9k** [comment]
This PR got super seeded by #1501 and #1466 thanks for the PR @campagnola !

**Pull request closed without merging**
