### PR TITLE
Adding project MiniPTI to README

### PR DESCRIPTION
**Pull request by bilaljo**
README.md
    
I'm using PyQtGraph for my GUI in the project MiniPTI on GitHub (as part from the EU project [Passepartout](https://cordis.europa.eu/project/id/101016956)) and would like to add it to the list of "who uses the library".

https://github.com/bilaljo/MiniPTI

### CODE REVIEW

**Comment by j9ac9k** [comment]
Hi @bilaljo 

Thanks for the PR!

Looks like something got messed up in the git commit histories you're attempting to merge, and 33 commits are trying to merged in with changes to 17 files... Can you update the source branch to clean up the git commit history/sync issues?  Also, not a deal breaker, but probably would be good to have a screenshot of the GUI on the README (nice to see what pyqtgraph looks like in your tool) ...but again not necessary.

**Comment by j9ac9k** [comment]
Hi @bilaljo 

I think the source and target branches are still wrong, it shows up as you trying to merge into a dependabot branch instead of master...let me know if you need help sorting out the git confusion.

**Comment by bilaljo** [comment]
Hi @j9ac9k 
thank you for your reply. Great idea, I'll add a picture of it (I have to do some refactoring before it's ready, but it is on my to-do list).

I think I need help, probably I choose the wrong branch. How can I fix it?

**Comment by j9ac9k** [comment]
> I think I need help, probably I choose the wrong branch. How can I fix it?

You have a couple of things going on, on your PR you are trying to merge _from_ `master`

image


See the branch names, I think if you press the edit button, you can change it so that it goes from bilaljo/<your-branch-name> -> pyqtgraph/master.  

I would start with that and see how github resolves this PR then.

**Comment by bilaljo** [comment]
Ah okay, now I understand. I actually cannot find it. May I close it and create another request? Intwo which branch should I commit in this case than?

**Pull request merged**
