### PR TITLE
Add NonUniformImage, example and tests.

### PR DESCRIPTION
**Pull request by t-sommer**
We've used this class extensively to visualize our simulation results and we'd like to contribute it to your library. Its functionality is similar to [matplotlib.image.NonUniformImage](https://matplotlib.org/api/image_api.html#matplotlib.image.NonUniformImage).

### CODE REVIEW

**Comment by j9ac9k** [comment]
Hi @t-sommer thanks for this PR, and thanks for including some test code!  I'm interested in getting this merged in, I'll download/test locally and follow up before much longer.  I know it's been a while since you submitted this, since you submitted this have there been any changes on your end that you'd like to incorporate?

**Comment by t-sommer** [comment]
I have not made any changes to the code. Please get back to me if you have any questions.

**Comment by Dschoni** [comment]
https://dev.azure.com/pyqtgraph/pyqtgraph/_build/results?buildId=348

**Comment by t-sommer** [comment]
> E                   Exception: Test standard /home/vsts/.pyqtgraph/test-data/nonuniform_image/colormap-3x3.png does not exist. Set PYQTGRAPH_AUDIT=1 to add this image.

You can pull the missing images from https://github.com/t-sommer/test-data/tree/nonuniform_image/nonuniform_image

**Comment by j9ac9k** [comment]
Looks like some combination fo Python2 or Qt4 doesn't like this PR.  I want to get this merged, but we may have to wait until 0.12 (or 1.0? whatever we decide to number the next version)

**Comment by j9ac9k** [comment]
Closing and Re-Opening to trigger new CI run

**Comment by j9ac9k** [comment]
Been wanting to merge this forever, now that we've killed off Qt4 support; it's happening 🎊 .  Thank you so much for the contribution @t-sommer !

**Comment by j9ac9k** [comment]
Hi @t-sommer 

Not sure if you're using NonUniformImage in your work, I realized recently that despite being added to the library, it's not actually documented.  When going to add documentation, I decided to mess with the methods some so it is more in line with the rest of the library.

Since it was never documented, the question of if it's part of the public API is not so black and white.  Before I go making tons of changes, I wanted to see if there would be breakage on your end, and if so, if it would be worth going through a deprecation dance/cycle when needed.

Hope all is well.

**Comment by t-sommer** [comment]
Please change the API if it improves the consistency and usability!

**Pull request merged**
