### PR TITLE
Correction of a bug in the removeHandle method of PolyLineROI

### PR DESCRIPTION
**Pull request by lesauxvi**
I had some troubles trying to restore the state of PolyLineROI objects using the setState method. This simple modification fixed the problem. 

Here is the error message I got (if it helps):

  `File "/home/lesaux/Documents/Belenos/belenos/plottingwidgets/ImageWidgetFull.py", line 305, in addPolyLineROI`
    `polyLine.setState(params)`

  `File "/home/lesaux/Documents/Belenos/belenos/pyqtgraph/graphicsItems/ROI.py", line 1854, in setState`
    `self.clearPoints()`

  `File "/home/lesaux/Documents/Belenos/belenos/pyqtgraph/graphicsItems/ROI.py", line 1844, in clearPoints`
    `self.removeHandle(self.handles[0]['item'])`

  `File "/home/lesaux/Documents/Belenos/belenos/pyqtgraph/graphicsItems/ROI.py", line 1907, in removeHandle`
    `handles = [h['item'] for h in segments[1].handles]`
`IndexError: list index out of range`

### CODE REVIEW

**Comment by lesauxvi** [comment]
@campagnola and @ericdill , any chance one of you find the time to review this PR? I knwo it is quite long, but it is very interesting to my opinion.

**Comment by lesauxvi** [comment]
ping @campagnola  and @ericdill

**Comment by lesauxvi** [comment]
ping @campagnola and @ericdill

**Comment by lesauxvi** [comment]
Can this PR directly be integrated into #349 @campagnola ?

**Comment by campagnola** [comment]
I think #349 already corrects this behavior and a few other related issues. Can you verify that is the case?

**Comment by lesauxvi** [comment]
Yes, I'll check that and come back after.

**Comment by lesauxvi** [comment]
Actually, I created a custom Roi class. Will wait #349 is merged to check if this PR is still relevant.

**Comment by lesauxvi** [comment]
PR closed because #349 corrects this bug.

Thanks Luke!

**Pull request closed without merging**
