### PR TITLE
LegendItem: Enable customization of label text size and tests

### PR DESCRIPTION
**Pull request by dgoeries**
This improves a little bit the customization of the LegendItem.

- I use a default labelTextSize of 9pt at first. Suggestions?

### CODE REVIEW

**Comment by dgoeries** [comment]
Looks like I got trapped. The test is cracking locally even without changes to the LegendItem. I have to check

**Comment by j9ac9k** [comment]
well, that's an odd test failure; only PyQt5 pipelines failing ....looks like something actually crashed during `test_PolyLineROI`

I'm able to replicate the issue locally:

```
pyqtgraph/graphicsItems/tests/test_InfiniteLine.py ..                                                                                                                                          [ 71%]
pyqtgraph/graphicsItems/tests/test_LegendItem.py .                                                                                                                                             [ 72%]
pyqtgraph/graphicsItems/tests/test_PlotCurveItem.py .                                                                                                                                          [ 72%]
pyqtgraph/graphicsItems/tests/test_PlotDataItem.py .....                                                                                                                                       [ 75%]
pyqtgraph/graphicsItems/tests/test_ROI.py ..zsh: abort      pytest

~/Developer/pyqtgraph legend-text-size-tests* 2m 1s
```

**Comment by j9ac9k** [comment]
I'm getting this same failure on master, so a PR must have snuck in that's causing havok...

**Comment by j9ac9k** [comment]
I think I identified the issue in the library code, no clue how it went so long un-noticed!  ...After I merge #1399, I'll re-run the pipeline (you may need to rebase your branch, I'm not sure...)

**Comment by dgoeries** [comment]
Thanks, but it is not fully fixed :(

It still crashes in the poly ROI test

**Comment by j9ac9k** [comment]
> Thanks, but it is not fully fixed :(
> 
> 
> 
> It still crashes in the poly ROI test

This is soooo wired!

**Comment by j9ac9k** [comment]
well.... this is alarming:

```
pyqtgraph-pyqt5-latest ❯ pytest
========================================================== test session starts ===========================================================
platform darwin -- Python 3.8.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /Users/ogi/Developer/pyqtgraph, inifile: pytest.ini
plugins: forked-1.2.0, cov-2.10.0, xdist-1.32.0
collected 159 items

examples/test_examples.py .....................s........................s...................                                       [ 41%]
pyqtgraph/dockarea/tests/test_dock.py ...                                                                                          [ 43%]
pyqtgraph/dockarea/tests/test_dockarea.py .                                                                                        [ 44%]
pyqtgraph/exporters/tests/test_csv.py .                                                                                            [ 44%]
pyqtgraph/exporters/tests/test_hdf5.py ...                                                                                         [ 46%]
pyqtgraph/exporters/tests/test_image.py .                                                                                          [ 47%]
pyqtgraph/exporters/tests/test_matplotlib.py ....                                                                                  [ 49%]
pyqtgraph/exporters/tests/test_svg.py ..                                                                                           [ 50%]
pyqtgraph/graphicsItems/PlotItem/tests/test_PlotItem.py ....                                                                       [ 53%]
pyqtgraph/graphicsItems/ViewBox/tests/test_ViewBox.py ..s                                                                          [ 55%]
pyqtgraph/graphicsItems/ViewBox/tests/test_ViewBoxZoom.py ........                                                                 [ 60%]
pyqtgraph/graphicsItems/tests/test_ArrowItem.py .                                                                                  [ 61%]
pyqtgraph/graphicsItems/tests/test_AxisItem.py .....                                                                               [ 64%]
pyqtgraph/graphicsItems/tests/test_ErrorBarItem.py .                                                                               [ 64%]
pyqtgraph/graphicsItems/tests/test_GraphicsItem.py ..                                                                              [ 66%]
pyqtgraph/graphicsItems/tests/test_ImageItem.py ...                                                                                [ 67%]
pyqtgraph/graphicsItems/tests/test_InfiniteLine.py ..                                                                              [ 69%]
pyqtgraph/graphicsItems/tests/test_LegendItem.py .                                                                                 [ 69%]
pyqtgraph/graphicsItems/tests/test_PlotCurveItem.py .                                                                              [ 70%]
pyqtgraph/graphicsItems/tests/test_PlotDataItem.py .....                                                                           [ 73%]
pyqtgraph/graphicsItems/tests/test_ROI.py ..zsh: abort      pytest

~/Developer/pyqtgraph legend-text-size-tests* 1m 56s
pyqtgraph-pyqt5-latest ❯ pytest -k "test_ROI"
========================================================== test session starts ===========================================================
platform darwin -- Python 3.8.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /Users/ogi/Developer/pyqtgraph, inifile: pytest.ini
plugins: forked-1.2.0, cov-2.10.0, xdist-1.32.0
collected 159 items / 156 deselected / 3 selected

pyqtgraph/graphicsItems/tests/test_ROI.py ...                                                                                      [100%]

=================================================== 3 passed, 156 deselected in 4.35s ====================================================

~/Developer/pyqtgraph legend-text-size-tests*
pyqtgraph-pyqt5-latest ❯
```

**Comment by dgoeries** [comment]
Thanks for debugging my tests! Pipeline is passing now

**Comment by j9ac9k** [comment]
Thanks for updating the PR @dgoeries those segfaults are _really_ annoying to troubleshoot, I'm just happy the issue was straight forward to spot.

I added one more comment, that instead of having an assert check to make sure the right type, do an if statement, and perhaps emit a warning message and return None without attempting to modify the size.  Alternatively you can just not do any checks and hope that whatever error handling Labeltem does would be sufficient (which I think would be fine too).

**Comment by dgoeries** [comment]
The error handling in the LabelItem is okay, it will throw. Changes were made, thanks for the review and help

**Comment by j9ac9k** [comment]
no problem, thanks for the PR, the build_docs stage will fail (for unrelated reasons), so don't worry about.  Assuming everything else is good, I'll merge.  Thanks again

**Comment by j9ac9k** [comment]
LGTM, thanks for the PR, merging.

**Comment by dgoeries** [comment]
Thanks, I will have two more PR's for the legend. :-)

**Pull request merged**
