### PR TITLE
Fix PixelVectors cache

### PR DESCRIPTION
**Pull request by erikmansson**
Suggested fix for issue #1189 where I stumbled upon an issue with the PixelVectors cache. See the issue for more details.

### CODE REVIEW

**Comment by j9ac9k** [comment]
Hmm, all linux CI runs are failing, but not just on this PR, but on another one as well... wonder if there is some upstream issue.

**Comment by 2xB** [comment]
The linux CI tests fail in pyvirtualdisplay, and that was recently updated, i.e. yesterday and the day before yesterday: https://pypi.org/project/PyVirtualDisplay/#history

It causes an issue in `pytest-xvfb`, already reported here:
https://github.com/The-Compiler/pytest-xvfb/issues/22

We could either ignore it for now, awaiting the update in one of the above modules, or pin `pyvirtualdisplay` to version 0.2.5.

### More info:
#### End of traceback:
```
  File "/usr/share/miniconda/envs/test-environment-3.6/lib/python3.6/site-packages/pyvirtualdisplay/abstractdisplay.py", line 313, in stop
    raise XStartError("stop() is called before start().")
pyvirtualdisplay.abstractdisplay.XStartError: stop() is called before start().
```
#### End of internal pytest error stack:
```
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment-3.7/lib/python3.7/site-packages/pytest_xvfb.py", line 46, in start
INTERNALERROR>     self._virtual_display.cmd.extend(self.args)
INTERNALERROR> AttributeError: 'Display' object has no attribute 'cmd'
```

**Comment by j9ac9k** [comment]
@2xB figured it had to do w/ the virtual display, but hadn't had a chance to do anything more than glance at it... I'll read a bit more when I get the kids to bed and try and figure out a course of action....on one hand we should ignore, on the other hand, I hate red from the CI.

**Comment by j9ac9k** [comment]
Closing/Reopening the PR to trigger a new CI run.

**Comment by campagnola** [comment]
Looks great to me. Thanks @erikmansson !

**Pull request merged**
