### PR TITLE
use single generic template for all bindings

### PR DESCRIPTION
**Pull request by pijyoi**
Currently, each `.ui` file has a separate generated `.py` file for each of the 4 bindings.

This PR demonstrates that the currently supported bindings are sufficiently similar that a single generic "generated" file can be used for all bindings. The generic "generated" file is actually a hand-modified version of the files churned out by PyQt6's `pyuic6`.

One benefit of doing this would be to make it easier for users who use `py2exe`, `pyinstaller` or similar programs. These programs seem to have issues with bundling files imported using the following statement. (#2122, #2179, #1981, #1934, #1811, #1801)
```python
ui_template = importlib.import_module(
    f'.exportDialogTemplate_{QT_LIB.lower()}', package=__package__)
```

Disclaimer: Not being a user of any of these freezing / bundling programs, I can't say for certain that this PR would make those programs include the needed files.

Note: flowchart, canvas, console modules were left out since they are not much used.

### CODE REVIEW

**Comment by pijyoi** [comment]
By deleting the non-generic files, it becomes clear from the git history that the generic files are just a rename of the *_pyqt6.py files with a one-line modification.

**Comment by j9ac9k** [comment]
The only other thing I can think of that should probably be part of this PR is that `rebuildUi.py` should be updated to _only_ work on PyQt6 bindings, write out to `*_generic.py` and change the import statements so they import from pyqtgraph's abstraction layer.

**Comment by pijyoi** [comment]
The automatic rewrite of the import line would need to handle different depth relative imports (for the library) and absolute imports (for the examples).

It would also be relying on pyuic6 output to remain the same style.

**Comment by j9ac9k** [comment]
Forgot about the relative import, that would indeed be trickier (and frankly just add un-needed complexity here).  Probably not worth the effort.

**Comment by pijyoi** [comment]
On a whim, I tried using `pyinstaller` (for the first time) on one of my scripts in a clean environment with `pyqtgraph 0.12.4`, `PySide6` and `numpy`. It seemed to just work (* with a little tweak) and I didn't encounter the issues listed before about missing template files and missing icon files.

(*) The colormap files were missing, so I changed my script to not use them.

Digging a bit, it seems that someone has taught `pyinstaller` about `pyqtgraph` template files.
https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/1649c5e412e02f5ebee4c542093064c8ba1c96bb/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyqtgraph.py

**Comment by j9ac9k** [comment]
Thanks for this @pijyoi 

Hopefully, this will make life easier for the folks doing freezing.

**Pull request merged**
