### PR TITLE
Fixes incorrect default value for scale parameter in makeARGB.

### PR DESCRIPTION
**Pull request by titusjan**
Fixes issue #792

### CODE REVIEW

**Comment by j9ac9k** [comment]
CI fails on this PR as it currently stands:

https://dev.azure.com/pyqtgraph/pyqtgraph/_build/results?buildId=259

**Comment by campagnola** [comment]
Looks good to me; I agree with @titusjan's assessment in #792. Unit tests in `pyqtgraph/tests/test_functions.py : test_makeARGB()` will need to be updated to reflect the change, and we definitely want a CHANGELOG entry noting the behavior change.

**Comment by Dschoni** [comment]
https://dev.azure.com/pyqtgraph/pyqtgraph/_build/results?buildId=347

**Comment by j9ac9k** [comment]
I fixed the test cases so they now pass; not exactly sure what should be stated in `CHANGELOG` specifically.  I'm going to leave the CHANGELOG update to be handled by #1005

**Comment by titusjan** [comment]
Sorry for my lack of response on this and thanks for fixing the tests.

**Comment by j9ac9k** [comment]
Don't sweat it, thanks for the PR and the analysis you did in #792

**Comment by Dschoni** [comment]
Does that indeed fix #792? As it is still open. If so, I would put exactly that in CHANGELOG.

**Comment by j9ac9k** [comment]
Yeah I meant to close it, my mistake.

**Pull request merged**
