### PR TITLE
Use base_prefix to detect virtual env

### LINKED ISSUE #1052: Multiprocess does not work in a venv
### Short description
The multiprocessing module does not work in a python3 venv on windows. This is related to the use of Popen to create a new python instance, and incorrect detection of PID

### Code to reproduce
1. Create a new venv:
```bash
$ mkdir tempvenv
$ cd tempvenv
$ python3 -m venv .
```
2. Try to spawn a multiprocess version of pyqtgraph
```python
import pyqtgraph as pg
import pyqtgraph.multiprocess as mp
app = pg.mkQApp()
rp = mp.QtProcess()
ros = rp._import("os")
```

### Expected behavior
The last line should return a remote proxy to the os module on the remote python instance.

### Real behavior
We get a key error:
```pytb
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
c:\users\x\documents\pyqtgraph\pyqtgraph\multiprocess\remoteproxy.py in handleRequest(self)
    210             print(optStr)
    211             print(os.getpid())
--> 212             opts = pickle.loads(optStr)
    213             self.debugMsg("    handleRequest: id=%s opts=%s", reqId, opts)
    214             #print os.getpid(), "received request:", cmd, reqId, opts

c:\users\x\documents\pyqtgraph\pyqtgraph\multiprocess\remoteproxy.py in unpickleObjectProxy(processId, proxyId, typeStr, attributes, opts)
    735         return obj
    736     else:
--> 737         proxy = ObjectProxy(processId, proxyId=proxyId, typeStr=typeStr)
    738         if opts is not None:
    739             proxy._setProxyOptions(**opts)

c:\users\x\documents\pyqtgraph\pyqtgraph\multiprocess\remoteproxy.py in __init__(self, processId, proxyId, typeStr, parent)
    805         }
    806
--> 807         self.__dict__['_handler'] = RemoteEventHandler.getHandler(processId)
    808         self.__dict__['_handler'].registerProxy(self)  ## handler will watch proxy; inform remote process when the proxy is deleted.
    809

c:\users\x\documents\pyqtgraph\pyqtgraph\multiprocess\remoteproxy.py in getHandler(cls, pid)
     93     def getHandler(cls, pid):
     94         try:
---> 95             return cls.handlers[pid]
     96         except:
     97             print(pid, cls.handlers)

KeyError: 12608
```

### Tested environment(s)

 * PyQtGraph version: 0.11.0.dev0 (ed6586c7)
 * Qt Python binding: PyQt5 5.12.3 Qt 5.12.5
 * Python version: Python 3.7.4
 * Operating system: Windows 10

### Additional context
The reason this occurs is because in a venv on windows, python creates a stub executable in the venv, which then spawns a real instance of python.

This causes the detected PID of the child process to not match with the child process stored in `RemoteEventHandler.handlers`.

We can see this with a minimal example on windows. Running inside the venv:
```python
import os, sys, time
from subprocess import Popen

def info(title):
    print(title)
    print('module name:', __name__)
    print('parent process:', os.getppid())
    print('process id:', os.getpid())

if __name__ == '__main__':
    if len(sys.argv) == 1:
        info("Parent Process")
        p = Popen((sys.executable, __file__, "proc"))
        print("Detected Child PID:", p.pid)
        while p.poll() is None:
            time.sleep(1)
    else:
        info("Child Process")
```
I get the output:
```
Parent Process
module name: __main__
parent process: 10220
process id: 17508
Detected Child PID: 10100
Child Process
module name: __main__
parent process: 10100
process id: 17480
```
Note that the detected child PID is 10100, while the child itself thinks it has the PID 17480. The child's parent process is 10100, which is the PID of the stub `python.exe` that venv creates.

### Potential Solutions
- Using `multiprocessing.Process` does not have this issue.
- Send the child PID back once the child has spawned.

### PR DESCRIPTION
**Pull request by eendebakpt**
See the discussion in #1860.

Detect presence of a virtual enviroment using `sys.prefix != sys.base_prefix`. This is more robust than a check on the environment variable `VIRTUAL_ENV`.

Fixes #1052

@j9ac9k @pijyoi 

A minimal example (using Windows):

1. Create a virtual environment using virtualenv
2. Activate the environment
3. Run `python -c "import os; print(os.environ.get('VIRTUAL_ENV'))"`. The output shows the location of the virtualenv
4. Install Spyder (`pip install spyder`)
5. Start spyder (by typing the command `spyder`). In the Spyder console window run `import sys; print(sys.prefix)`. The output is the location of the virtual environment, which shows the console session in spyder is indeed running the virtual environment.
7. In the same console window of spyder run `import os; print(os.environ.get('VIRTUAL_ENV'))`. The output is `None`. So the original check does not work in this case
7. In the same console window run `import sys; sys.prefix != sys.base_prefix`. The output is `True`

### Other Tasks 

<details>
  <summary>Bump Dependency Versions</summary>

### Files that need updates
    
Confirm the following files have been either updated or there has been a determination that no update is needed.

- [ ] `README.md`
- [ ] `setup.py`
- [ ] `tox.ini`
- [ ] `.github/workflows/main.yml` and associated `requirements.txt` and conda `environemt.yml` files
- [ ] `pyproject.toml`
- [ ] `binder/requirements.txt`

</details>

<details>
    <summary>Pre-Release Checklist</summary>

### Pre Release Checklist

- [ ] Update version info in `__init__.py`
- [ ] Update `CHANGELOG` primarily using contents from automated changelog generation in GitHub release page
- [ ] Have git tag in the format of pyqtgraph-<version>

</details>

<details>
  <summary>Post-Release Checklist</summary>

### Steps To Complete

- [ ] Append `.dev0` to `__version__` in `__init__.py`
- [ ] Announce on mail list
- [ ] Announce on Twitter

</details>

### CODE REVIEW

**Comment by pijyoi** [comment]
Is this not an issue with Spyder messing with the environment?
https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/ipythonconsole/utils/kernelspec.py#L173

**Comment by pijyoi** [comment]
IPython makes use of the VIRTUAL_ENV environment variable and Spyder wants to fool IPython.
https://github.com/ipython/ipython/blob/27ca9e2e3f8c9220a8b92938e11157a77c2c4893/IPython/core/interactiveshell.py#L845

Maybe the fix should be at Spyder?

**Comment by eendebakpt** [comment]
> IPython makes use of the VIRTUAL_ENV environment variable and Spyder wants to fool IPython. https://github.com/ipython/ipython/blob/27ca9e2e3f8c9220a8b92938e11157a77c2c4893/IPython/core/interactiveshell.py#L845
> 
> Maybe the fix should be at Spyder?

@pijyoi Thanks for the pointer, that gives good information. I do not know whether we should fix this at the spyder or pyqtgraph side. I created https://github.com/spyder-ide/spyder/issues/20273 to get input from the spyder devs.

The PR here is simple, so if there are no downsides and there is no easy solution at the spyder side I would be in favor of this option.

**Comment by j9ac9k** [comment]
Hi @eendebakpt 

I'm ok merging this change, but I would request you add a comment with a link to the issue in spyder, so that future people maintaining the library don't have to scratch their heads as to why this change was made, and in turn can track if the other issue was ever fixed (and if it is fixed/addressed, when can this patch be removed from pyqtgraph).

**Comment by eendebakpt** [comment]
> Hi @eendebakpt
> 
> I'm ok merging this change, but I would request you add a comment with a link to the issue in spyder, so that future people maintaining the library don't have to scratch their heads as to why this change was made, and in turn can track if the other issue was ever fixed (and if it is fixed/addressed, when can this patch be removed from pyqtgraph).
> 
> EDIT: btw thanks for creating the issue w/ the Spyder repo; hopefully there will be an explanation there, ccordoba12 (intentionally not tagging to minimize notification spam) is a friend of the project :)

@j9ac9k No response on the spyder github issue yet, but I added links to the issues in the comments.

**Comment by j9ac9k** [comment]
> > Hi @eendebakpt
> > I'm ok merging this change, but I would request you add a comment with a link to the issue in spyder, so that future people maintaining the library don't have to scratch their heads as to why this change was made, and in turn can track if the other issue was ever fixed (and if it is fixed/addressed, when can this patch be removed from pyqtgraph).
> > EDIT: btw thanks for creating the issue w/ the Spyder repo; hopefully there will be an explanation there, ccordoba12 (intentionally not tagging to minimize notification spam) is a friend of the project :)
> 
> @j9ac9k No response on the spyder github issue yet, but I added links to the issues in the comments.

Thanks, that's perfect!

**Pull request merged**
