### PR TITLE
made gradients a private variable, added addPreset function

### PR DESCRIPTION
**Pull request by mfarhan12**

### CODE REVIEW

**Comment by campagnola** [comment]
This looks good, but please don't mix in style changes.

**Comment by mfarhan12** [comment]
What do you mean by style changes?, I removed all of the '##' comments because Travis CI was complaining about them.

**Comment by campagnola** [comment]
Gotcha, that's my fault--I need to disable the travis checks.

**Comment by campagnola** [comment]
Ok, I looked a bit closer and I'm not sure I understand the purpose of this PR. Can you clarify how you think `addPreset()` would be used?

**Comment by j9ac9k** [comment]
Closing due to no follow up from author.

**Pull request closed without merging**
