### PR TITLE
Fix aspectRatio and zoom range issues when zooming

### PR DESCRIPTION
**Pull request by ibrewster**
- fixes issue #1030 
- Moves range check logic out of the updateViewRange function into the setRange function, forcing the requested range into limits
- Modifies the aspect ratio check logic to keep the final aspect ratio corrected viewRange within any set limits
- Added a test module testing the above features. There are many more combinations of limits/zoom requests that could be tested, I'm sure, but I tried to cover the major areas.

I noticed that my IDE "cleaned up" a bunch of blank lines, which made it into the commit. Sorry about the noise!

### CODE REVIEW

**Comment by ibrewster** [comment]
I do apologize for the numerous "junk" commits here - I don't know how to remove them from the pull request.

**Comment by j9ac9k** [comment]
Thanks @ibrewster for the PR including the tests!  No problem on the "junk commits" I'll squash before merging.... as the viewbox is very fragile, I do want to spend some time experimenting with this, I'll try and make the time in the next few days.

**Comment by j9ac9k** [comment]
Closing/Opening to re-trigger CI

**Comment by j9ac9k** [comment]
Hi @ibrewster sorry it's taken me so long to follow up.  These changes look fantastic to me, thanks for the comments and the tests.  I'm going to close/re-open this PR to trigger a new CI run, if it passes, I'll go ahead and merge.

**Comment by j9ac9k** [comment]
CI came back all green, thanks for this PR @ibrewster merging!

**Comment by ibrewster** [comment]
Glad to hear it, and happy I could help!

**Pull request merged**
