### PR TITLE
Fix Matplotlib color map import, add CC0 maps locally

### PR DESCRIPTION
**Pull request by NilsNemitz**
The latest version of Matplotlib updated some color maps, e.g. "Blues". These now report their data as numpy arrays, which is not handled in the current importer code. This PR changes the import to also accept data in this format.

Thanks to @edumur for pointing this out!

To reduce the dependency on the Matplotlib importer, I have added the new matplotlib color maps viridis, plasma, magma, and inferno to the locally stored data, so that they can be imported with e.g. `pg.colormap.get('viridis')`. The creators have been awesome and made these maps available under a public domain CC0 license. Thank you very much to Nathaniel J. Smith, Stefan van der Walt and Eric Firing!

The included data has been reformatted from the source at https://bids.github.io/colormap/

### CODE REVIEW

**Comment by edumur** [comment]
Hello,

Since we are adding some csv files around, allowing local import without having to install matplotlib or others, what about adding other files like:
* turbo: https://gist.github.com/mikhailov-work/ee72ba4191942acecc03fe6da94fc73f
* cividis: https://github.com/pnnl/cmaputil

image

**Comment by j9ac9k** [comment]
Hi @edumur 

I'm supportive of adding more color maps; I'm not sure it needs to happen in this PR (despite this PR does add colormaps) primarily due to this PR meant to address a chance in matplotlib's handling of color maps... I'll let @NilsNemitz decide which way to go here tho.

**Comment by edumur** [comment]
Sure!

I would be happy to propose another PR with the other colormaps after this one is done correcting the pml thing.

**Comment by NilsNemitz** [comment]
Dear @edumur, I am looking forward to more suggestions!
We can add more color map data at any time, and there are already some additional ideas regarding color maps.

As a final step for this round, I have updated the PR to also include the _cividis_ color map, optimized to help data interpretation by those affected by color vision deficiencies. 

The motivation and construction of this color map is described in full detail in the article "Optimizing colormaps with consideration for color vision deficiency to enable accurate interpretation of scientific data" which is published under a CC0 license in the scientific journal PLoS ONE, and includes the map data as a supplementary file.
http://dx.doi.org/10.1371/journal.pone.0199239

Thank you very much to Jamie R. Nuñez, Christopher R. Anderton and Ryan S. Renslow for their awesome work!

In addition to this addition I have changed the sorting of the color maps in the example to prioritize lower case names. This moves the newly added and commonly used maps viridis, inferno, plasma, magma and cividis to the top of the list.

**Comment by j9ac9k** [comment]
Doing some searching, looks like Jamie R. Nuñez is on github, so thank you @jamienunez (couldn't tell with certainty if the other authors were on here) for your work on this!

**Pull request merged**
