### PR TITLE
Fix autosize not taking to correct range with TextItem in view

### PR DESCRIPTION
**Pull request by j9ac9k**
When pressing the auto-scale button, the scale can be taken to an incorrect scale, or if you zoom out _way_ too far, it can be taken to some bogus range.

Issue #1373 discusses a little more of the troubleshooting effort, eventually stumbled across the the first-call to ViewBox.updateMatrix in ViewBox.resizeEvent was causing the issue.

### CODE REVIEW

**Comment by j9ac9k** [comment]
There's always that one config that fails on that one test....rerunning the test didn't fix the issue unfortunately... I should look at this test a bit more carefully

**Comment by j9ac9k** [comment]
This should do it, I couldn't come up with a test that worked reliably unfortunately... hopefully this doesn't break stuff, as ViewBox.py is crazy sensitive.

**Comment by misantroop** [comment]
This commit causes a 30-40% slowdown on ViewBox update in my case. Something related to the removal of update() and prepareForPaint() called in paint().

**Comment by j9ac9k** [comment]
> This commit causes a 30-40% slowdown on ViewBox update in my case. Something related to the removal of update() and prepareForPaint() called in paint().

You're not the first person to suggest this, and I'm working on some potential fixes, but I've had a tough time with a benchmark showing a difference that isn't a rounding error.  If you have a use-case that demonstrates a 30-40% difference in performance, can you please post it to #1602 so I can test with that?

**Comment by misantroop** [comment]
> 
> 
> > This commit causes a 30-40% slowdown on ViewBox update in my case. Something related to the removal of update() and prepareForPaint() called in paint().
> 
> You're not the first person to suggest this, and I'm working on some potential fixes, but I've had a tough time with a benchmark showing a difference that isn't a rounding error. If you have a use-case that demonstrates a 30-40% difference in performance, can you please post it to #1602 so I can test with that?

Project too big to post. What about the PlotSpeedTest with autoscale example? I get 155 fps in 0.11.0 vs 95 fps in 0.11.1.

**Pull request merged**
