### PR TITLE
Fix the wrong conversion of QVector3D to numpy array in GLViewWidget.py

### PR DESCRIPTION
**Pull request by 3DAlgoLab**
Fix the wrong conversion of QVector3D to numpy array.

### CODE REVIEW

**Comment by j9ac9k** [comment]
Hi @3DAlgoLab 

Thanks for re-submitting the PR.  I've been taking a look at the codebase and I'm confused how this error occurred to begin with.

Here is the cameraPosition method:

```python
    def cameraPosition(self):
        """Return current position of camera based on center, dist, elevation, and azimuth"""
        center = self.opts['center']
        dist = self.opts['distance']
        if self.opts['rotationMethod'] == "quaternion":
            pos = center - self.opts['rotation'].rotatedVector( Vector(0,0,dist) )
        else:
            # using 'euler' rotation method
            elev = radians(self.opts['elevation'])
            azim = radians(self.opts['azimuth'])
            pos = Vector(
                center.x() + dist * cos(elev) * cos(azim),
                center.y() + dist * cos(elev) * sin(azim),
                center.z() + dist * sin(elev)
            )
        return pos
```

as far as I can tell, `self.opts['center']` is _always_ a `Vector` object;

Do you happen to have the code handy that broke this?

**Comment by 3DAlgoLab** [comment]
> Hi @3DAlgoLab
> 
> Thanks for re-submitting the PR. I've been taking a look at the codebase and I'm confused how this error occurred to begin with.
> 
> Here is the cameraPosition method:
> 
> ```python
>     def cameraPosition(self):
>         """Return current position of camera based on center, dist, elevation, and azimuth"""
>         center = self.opts['center']
>         dist = self.opts['distance']
>         if self.opts['rotationMethod'] == "quaternion":
>             pos = center - self.opts['rotation'].rotatedVector( Vector(0,0,dist) )
>         else:
>             # using 'euler' rotation method
>             elev = radians(self.opts['elevation'])
>             azim = radians(self.opts['azimuth'])
>             pos = Vector(
>                 center.x() + dist * cos(elev) * cos(azim),
>                 center.y() + dist * cos(elev) * sin(azim),
>                 center.z() + dist * sin(elev)
>             )
>         return pos
> ```
> 
> as far as I can tell, `self.opts['center']` is _always_ a `Vector` object;
> 
> Do you happen to have the code handy that broke this?

Here is how I used. The exception occurred after changing 'rotationMethod' from 'Euler' to 'Quartenion'. 

self.glv = GLViewWidget()
... 
self.glv.reset()  # reset parameters
self.glv.clear()  # remove all items
self.glv.opts['distance'] = abs(center_pt[-1])
self.glv.opts['center'] = Vector(center_pt)
self.glv.opts['rotationMethod'] = 'quaternion'
self.glv.opts['rotation'] = QQuaternion.fromDirection(QVector3D(0, 0, -1),
                                                              QVector3D(0, -1, 0))

**Comment by j9ac9k** [comment]
thanks for sharing, I'll  give this a run through tonight or tomorrow.

**Comment by j9ac9k** [comment]
Hi @3DAlgoLab I'm still trying to replicate this issue, but I'm not having any success.  I know this PR is a minor code change, and the code change on its own doesn't concern me, but if there is an unexpected code path, I'd like to know about it.

I've been modifying some of the openGL examples in the example directory, specifically I've modified the [GLViewWidget.py ](https://github.com/pyqtgraph/pyqtgraph/blob/master/examples/GLViewWidget.py)and [GLVolumeItem.py](https://github.com/pyqtgraph/pyqtgraph/blob/master/examples/GLVolumeItem.py) examples; but haven't been able to generate this error there.

Are you able to modify any of the examples such that the same error is generated?

**Comment by 3DAlgoLab** [comment]
Actually I found that error when I use GLScatterPlotItem. 
Following is the full code. In my real code, I read some vendor specific point cloud file. But here, it generates some random distributed points. 

```python

# Test program loading Point Cloud Ply file


import sys
from PyQt5.QtWidgets import (QMainWindow, QVBoxLayout, QWidget,
                             QPushButton, QApplication)
from PyQt5.QtGui import QQuaternion, QVector3D

from pyqtgraph.opengl import (GLAxisItem, GLViewWidget,
                              GLScatterPlotItem)

from pyqtgraph import Vector
import numpy as np


class MainWindow(QMainWindow):
    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        w = QWidget()
        self.setGeometry(10, 10, 640, 480)
        self.setCentralWidget(w)
        w.setLayout(QVBoxLayout())

        lo = w.layout()
        self.glv = GLViewWidget()
        self.glv.opts['distance'] = 20

        self.setWindowTitle("3D View")

        btn_start = QPushButton("Show Info")
        btn_start.pressed.connect(self.show_info)

        lo.addWidget(btn_start)
        lo.addWidget(self.glv)

        self.load_point_cloud()

    def show_info(self):
        print("Cam pos:", self.glv.cameraPosition())
        opts = self.glv.opts
        # print("elevation: ", opts['elevation'])
        # print("azimuth: ", opts['azimuth'])
        # print("rotation: ", opts['rotation'])
        # print(opts)

    def load_point_cloud(self):        
        N = 10000

        xyz = np.random.normal(size=(N, 3))*300.0 + np.float32([[0, 0, 600]])
        rgba = np.ones((N, 4)) * 255
        rgba[:, :3] = np.random.uniform(0, 255, size=(N, 3))

        print("Before filtering...:", len(xyz))

        # Analysis
        mask = ~np.any(np.isnan(xyz), axis=1)
        xyz = xyz[mask]
        rgba = rgba[mask]

        print("After filtering...:", len(xyz))

        max_pt = xyz.max(axis=0)
        min_pt = xyz.min(axis=0)
        center_pt = (max_pt + min_pt) * 0.5
        print("max pt: ", max_pt)
        print("min pt: ", min_pt)
        print("center: ", center_pt)

        print("rgba avg.:", rgba.mean(axis=0))

        self.glv.reset()  # reset parameters
        self.glv.clear()  # remove all items
        self.glv.opts['distance'] = abs(center_pt[-1])
        self.glv.opts['center'] = Vector(center_pt)
        self.glv.opts['rotationMethod'] = 'quaternion'
        self.glv.opts['rotation'] = QQuaternion.fromDirection(QVector3D(0, 0, -1),
                                                              QVector3D(0, -1, 0))

        ax = GLAxisItem()
        ax.setSize(50, 50, 50)
        self.glv.addItem(ax)

        sp = GLScatterPlotItem(pos=xyz, color=rgba / 255, size=0.5, pxMode=False)
        self.glv.addItem(sp)

        print("Current vis. items: ", self.glv.items)


def main():    
    app = QApplication(sys.argv)
    mw = MainWindow()
    mw.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()


```

**Comment by j9ac9k** [comment]
I ran this code, and this does indeed not work on Windows, but it generates the same error with the proposed PR as well; so I'm not sure this is the same issue.

**Comment by j9ac9k** [comment]
```
(.venv-pyqt5_515-py38) PS C:\Users\ogi\source\repos\j9ac9k\pyqtgraph> python problem.py
Before filtering...: 10000
After filtering...: 10000
max pt:  [1169.61099131 1215.94362109 1944.70705206]
min pt:  [-1106.19269105 -1097.66011344  -700.40733911]
center:  [ 31.70915013  59.14175383 622.14985648]
rgba avg.: [127.0777115  127.29197389 126.93830295 255.        ]
Traceback (most recent call last):
  File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\.venv-pyqt5_515-py38\lib\site-packages\OpenGL\latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable
```

That is the error I'm getting on Windows.

**Comment by 3DAlgoLab** [comment]
> ```
> (.venv-pyqt5_515-py38) PS C:\Users\ogi\source\repos\j9ac9k\pyqtgraph> python problem.py
> Before filtering...: 10000
> After filtering...: 10000
> max pt:  [1169.61099131 1215.94362109 1944.70705206]
> min pt:  [-1106.19269105 -1097.66011344  -700.40733911]
> center:  [ 31.70915013  59.14175383 622.14985648]
> rgba avg.: [127.0777115  127.29197389 126.93830295 255.        ]
> Traceback (most recent call last):
>   File "C:\Users\ogi\source\repos\j9ac9k\pyqtgraph\.venv-pyqt5_515-py38\lib\site-packages\OpenGL\latebind.py", line 43, in __call__
>     return self._finalCall( *args, **named )
> TypeError: 'NoneType' object is not callable
> ```
> 
> That is the error I'm getting on Windows. This error seems to be in the GLScatterItem on this line:
> 
> ```python
>         glActiveTexture(GL_TEXTURE0)
> ```
> 
> I don't know enough about the 3D components of this library to troubleshoot this; but I feel comfortable saying this PR does not fix that issue.

Indirect call of self.load_point_cloud works anyway and generate the error I met like this:
```
      pxSize = self.view().pixelSize(gpos)
    |    File "C:\Users\j2\Envs\3d\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 433, in pixelSize
    |      cam = np.array(cam).reshape((1,)*(pos.ndim-1)+(3,))
    |  ValueError: cannot reshape array of size 1 into shape (1,3)
    |==============================<<
Error while drawing item <pyqtgraph.opengl.items.GLScatterPlotItem.GLScatterPlotItem object at 0x000002D66FD989D8>.
[01:32:59]   
```
Please try following code in the windows 10. 

```python
import sys
from PyQt5.QtWidgets import (QMainWindow, QVBoxLayout, QWidget,
                             QPushButton, QApplication)
from PyQt5.QtGui import QQuaternion, QVector3D
from PyQt5.QtCore import Qt, QCoreApplication, QTimer

# QCoreApplication.setAttribute(Qt.AA_UseDesktopOpenGL)

from pyqtgraph.opengl import (GLAxisItem, GLViewWidget,
                              GLScatterPlotItem)

from pyqtgraph import Vector
import numpy as np


class MainWindow(QMainWindow):
    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        w = QWidget()
        self.setGeometry(10, 10, 640, 480)
        self.setCentralWidget(w)
        w.setLayout(QVBoxLayout())

        lo = w.layout()
        self.glv = GLViewWidget()
        self.glv.opts['distance'] = 20

        self.setWindowTitle("3D View")

        btn_start = QPushButton("Show Info")
        btn_start.pressed.connect(self.show_info)

        lo.addWidget(btn_start)
        lo.addWidget(self.glv)

        QTimer.singleShot(0, self.load_point_cloud)
        # self.load_point_cloud()

    def show_info(self):
        print("Cam pos:", self.glv.cameraPosition())
        opts = self.glv.opts
        # print("elevation: ", opts['elevation'])
        # print("azimuth: ", opts['azimuth'])
        # print("rotation: ", opts['rotation'])
        # print(opts)

    def load_point_cloud(self):        
        N = 10000

        xyz = np.random.normal(size=(N, 3))*300.0 + np.float32([[0, 0, 600]])
        rgba = np.ones((N, 4)) * 255
        rgba[:, :3] = np.random.uniform(0, 255, size=(N, 3))

        print("Before filtering...:", len(xyz))

        # Analysis
        mask = ~np.any(np.isnan(xyz), axis=1)
        xyz = xyz[mask]
        rgba = rgba[mask]

        print("After filtering...:", len(xyz))

        max_pt = xyz.max(axis=0)
        min_pt = xyz.min(axis=0)
        center_pt = (max_pt + min_pt) * 0.5
        print("max pt: ", max_pt)
        print("min pt: ", min_pt)
        print("center: ", center_pt)

        print("rgba avg.:", rgba.mean(axis=0))

        self.glv.reset()  # reset parameters
        self.glv.clear()  # remove all items
        self.glv.opts['distance'] = abs(center_pt[-1])
        self.glv.opts['center'] = Vector(center_pt)
        
        self.glv.opts['rotationMethod'] = 'quaternion'
        self.glv.opts['rotation'] = QQuaternion.fromDirection(QVector3D(0, 0, -1),
                                                              QVector3D(0, -1, 0))

        ax = GLAxisItem()
        ax.setSize(50, 50, 50)
        self.glv.addItem(ax)

        sp = GLScatterPlotItem(pos=xyz, color=rgba / 255, size=0.5, pxMode=False)
        self.glv.addItem(sp)

        print("Current vis. items: ", self.glv.items)


def main():        
    app = QApplication(sys.argv)    
    mw = MainWindow()
    mw.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
```

**Comment by pijyoi** [comment]
>That is the error I'm getting on Windows. This error seems to be in the GLScatterItem on this line:
        glActiveTexture(GL_TEXTURE0)
I don't know enough about the 3D components of this library to troubleshoot this; but I feel comfortable saying this PR does not fix that issue.

The above fails for the same reason as for https://github.com/pyqtgraph/pyqtgraph/issues/1787#issuecomment-844591636
i.e. with QOpenGLWidget, GLViewWidget must be shown before adding a GLScatterPlotItem.

That's why "Indirect call of self.load_point_cloud" works.

**Comment by pijyoi** [comment]
An alternate fix would be to ensure that ```cameraPosition()``` always returns a ```Vector``` instance.
```python
        if self.opts['rotationMethod'] == "quaternion":
            pos = center - self.opts['rotation'].rotatedVector( Vector(0,0,dist) )
            pos = Vector(pos)     # <-- new line
        else:
```

**Comment by 3DAlgoLab** [comment]
> > That is the error I'm getting on Windows. This error seems to be in the GLScatterItem on this line:
> > glActiveTexture(GL_TEXTURE0)
> > I don't know enough about the 3D components of this library to troubleshoot this; but I feel comfortable saying this PR does not fix that issue.
> 
> The above fails for the same reason as for [#1787 (comment)](https://github.com/pyqtgraph/pyqtgraph/issues/1787#issuecomment-844591636)
> i.e. with QOpenGLWidget, GLViewWidget must be shown before adding a GLScatterPlotItem.
> 
> That's why "Indirect call of self.load_point_cloud" works.

Thanks for your comment. But it worked in Ubuntu, with the direct call, strangely. The alternative fix you suggested looks more elegant and clear.

**Comment by 3DAlgoLab** [comment]
There is a more clear way to fix this issue.

**Pull request closed without merging**
