### PR TITLE
Disable paint in GLScatterPlotItem if it has no data

### LINKED ISSUE #1347: opengl\items\GLScatterPlotItem.py, Argument pos
### Description
pos is defined as an **empty list** in line 17 instead of an array which causes for exceptions when `pose.shape`, `pos.transpose()`, and `pos.size` are used.

### Behavior
```
    |==============================>>
    |  Traceback (most recent call last):
    |    File "filename.py", line 358, in <module>
    |      sys.exit(app.exec_())
    |    File "...\AppData\Roaming\Python\Python38\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 193, in paintGL      
    |      self.drawItemTree(useItemNames=useItemNames)
    |    File "...\AppData\Roaming\Python\Python38\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 233, in drawItemTree 
    |      self.drawItemTree(i, useItemNames=useItemNames)
    |    File "...\AppData\Roaming\Python\Python38\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 214, in drawItemTree 
    |      debug.printExc()
    |    --- exception caught here ---
    |    File "...\AppData\Roaming\Python\Python38\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 211, in drawItemTree 
    |      i.paint()
    |    File "...\AppData\Roaming\Python\Python38\site-packages\pyqtgraph\opengl\items\GLScatterPlotItem.py", line 152, in paint
    |      glDrawArrays(GL_POINTS, 0, int(pos.size / pos.shape[-1]))
    |  AttributeError: 'list' object has no attribute 'size'
    |==============================<<
Error while drawing item <pyqtgraph.opengl.items.GLScatterPlotItem.GLScatterPlotItem(0xf20aa30) at 0x101A63A8>.
```

### Additional context
I honestly have no idea how to fix it since I tried some of the trivia fixes, and they did not solve the problem. (
newbie)

### PR DESCRIPTION
**Pull request by ixjlyons**
Fixes #1347. The opengl stuff is definitely neglected but might as well fix up trivial stuff.

### CODE REVIEW

**Comment by j9ac9k** [comment]
PyQt6 pipelines will fail for unrelated reasons

**Comment by j9ac9k** [comment]
Just out of curiosity any reason you decided to use `None` and make `self.pos` an optional list, as opposed to leaving it as a list and doing a Boolean check on `self.pos` in the paint method?

**Comment by ixjlyons** [comment]
No particular reason. I guess it seemed weird to instantiate it as a list if it should only ever be an ndarray. `None` seems like more of a "not-yet-initialized attribute" than an empty list imo.

I didn't really put a whole lot of thought into it - there are probably dozens of low hanging fruit to fix up in `GLScatterPlotItem` and I was just combing through issues to close out easy ones.

**Comment by j9ac9k** [comment]
oh I didn't realize that `self.pos` was normally a ndarray; yeah definitely 100% onboard w/ the `None` implementation 👍

**Pull request merged**
