### PR TITLE
WIP: PySide2 support

### PR DESCRIPTION
**Pull request by campagnola**
Based off of maxpeng's work on #376 
Most of the infrastructure is in place, but there are still some major rendering issues to work out.

### CODE REVIEW

**Comment by campagnola** [comment]
Currently hung up on this bug:  https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-86?filter=allopenissues

**Comment by robbmcleod** [comment]
@campagnola any status update on this?  The PySide2 issues tracker indicates issue PYSIDE-86 is closed now, so it might be worth another try?

**Comment by stonebig** [comment]
testing to day on the last comit of this patch, and PySide2-5.9.0a1.dev1525348439-5.9.6-cp36-cp36m-win_amd64.whl:
````
import pyqtgraph.examples; pyqtgraph.examples.run()
````

Some Tests are going rather well. some other fails:
- "Optics" test: Object of type 'Mirror' as no len()
- "Koch Fractal" test: name 'reduce' is not defined
- "isocurve" test: slice indice must be integers or None or ...
- "Volumetric" : ... called with wrong argument types ...

==>I shall retest after official preview, end of may: it may mostly be PySide2 bugs.

**Comment by campagnola** [comment]
I tested with 5.11 and ended up with the same bug :(
I'll try out 5.9 next..

**Pull request merged**
