### PR TITLE
Export dialog: ParameterTree needs 2 columns

### PR DESCRIPTION
**Pull request by pijyoi**
To address #1728, where pyside{2,6}-uic.exe generate code that cause Parameter values to not show up.
The hand-edited version drops some redundant statements and reduces the verbosity of the original generated code.

### CODE REVIEW

**Comment by j9ac9k** [comment]
This PR should likely remove the binding specific template files as well.  

Another reason to ditch the binding specific templates is that pyinstaller (or any freezing application) has a tendency not to be able to recognize to import them from this statement:

```python
import importlib
ui_template = importlib.import_module(
    f'.exportDialogTemplate_{QT_LIB.lower()}', package=__package__)
```

and subsequently the frozen application doesn't work until the user manually adds it to the "hidden imports" section. 

Since I already have countless virtual environments on my system for various python/qt-binding combinations, I'll check this out.  My only question is should we add a test to see if _any_ parameter value shows up (this way `tox` could potentially identify problematic python/qt combinations).

**Comment by pijyoi** [comment]
I found an alternative, if a second column is added to the header of the ParameterTree, then the param values will get shown. The issue could thus be phrased as : "If you use a QWidgetTreeItem for the header, then it needs to have the same number of columns as the non-header items". This is a less invasive change than the previous commit. Whether this commit or the previous commit is preferable is arguable.

>Another reason to ditch the binding specific templates is that pyinstaller (or any freezing application) has a tendency not to be able to recognize to import them from this statement:

I see, so that's the unintended consequence of trying to simplify the code from the original if, else branches.

>My only question is should we add a test to see if any parameter value shows up (this way tox could potentially identify problematic python/qt combinations)

I don't know how to do that programmatically. Testing whether some widget got painted, that is.

**Comment by j9ac9k** [comment]
> I see, so that's the unintended consequence of trying to simplify the code from the original if, else branches.

For the record, while this is a nice to have, as a pyinstaller user, I don't feel the onus is on the pyqtgraph library to work w/ pyinstaller out of the box.  Pyinstaller gives enough debug info, and enough documentation that users should be able to sort it out.  In short, if things were equal, I would say let's go the way pyinstaller is less likely to break; but I don't think we should go too far out of our way.

> I don't know how to do that programmatically. Testing whether some widget got painted, that is.

Ahh, I was wondering if we could do something like `QWidgetTreeItem.isVisible()` or something like that... either way probably not the end of the world to leave as-is.

**Comment by pijyoi** [comment]
I think I found the right property to set in the ui file: columnCount. This should be the most direct fix.

The decision to hand-write the forms can be deferred.

**Comment by j9ac9k** [comment]
Confirmed this works, thanks @pijyoi for not only the fix, but identifying the fix with the most minimal change.  Merging.

**Pull request merged**
