### PR TITLE
BarGraphItem CSV/image export

### PR DESCRIPTION
**Pull request by Axel-Jacobsen**

### CODE REVIEW

**Comment by Axel-Jacobsen** [comment]
rerun

**Comment by j9ac9k** [comment]
For the record, the CI failure is due to something unrelated.

**Comment by j9ac9k** [comment]
BTW thanks for the PR @Axel-Jacobsen

**Comment by j9ac9k** [comment]
@Axel-Jacobsen Thanks for the PR and the very detailed issue writeup in #1007; this looks good to me, I'll be merging shortly.

**Pull request merged**
