### PR TITLE
MNT: Call close() up the inheritance chain

### LINKED ISSUE #280: GraphicsView fails to call its QGraphicsView inherited close method
This causes problems when e.g. a ``PlotWidget`` is used as top-level widget. The application would fail to exit when ``close`` is called.

```
--- a/pyqtgraph/widgets/GraphicsView.py
+++ b/pyqtgraph/widgets/GraphicsView.py
@@ -165,6 +165,7 @@ class GraphicsView(QtGui.QGraphicsView):
         self.sceneObj = None
         self.closed = True
         self.setViewport(None)
+        QtGui.QGraphicsView.close(self)
         
     def useOpenGL(self, b=True):
         if b:
```

### LINKED ISSUE #299: ImageView fails to call its inherited close method
Same problem as #280.

```
diff --git a/pyqtgraph/imageview/ImageView.py b/pyqtgraph/imageview/ImageView.py
index 61193fc..9d7ad2e 100644
--- a/pyqtgraph/imageview/ImageView.py
+++ b/pyqtgraph/imageview/ImageView.py
@@ -373,6 +373,7 @@ class ImageView(QtGui.QWidget):
         del self.image
         del self.imageDisp
         self.setParent(None)
+        QtGui.QWidget.close(self)
         
     def keyPressEvent(self, ev):
         #print ev.key()
```

### PR DESCRIPTION
**Pull request by ericdill**
Closes #280
Closes #299

### CODE REVIEW

**Comment by ericdill** [comment]
@sbourdeauducq does this solve your problem?

**Comment by sbourdeauducq** [comment]
#280 yes, but not #299.

**Comment by campagnola** [comment]
Looks good. @ericdill, can you apply the suggested change from #299 as well?

**Comment by ericdill** [comment]
@sbourdeauducq sorry for missing #299 on my first pass.  This should be working now.

@campagnola good to go

**Comment by ericdill** [comment]
bump @campagnola

**Comment by campagnola** [comment]
Awesome. Thanks @ericdill and @sbourdeauducq !

**Pull request merged**
