### PR TITLE
PlotDataItem: Fix view range <-> dynamic range limit pathology and switch to np.umath.clip

### PR DESCRIPTION
**Pull request by NilsNemitz**
Issue #1634 brought to light an issue with the current code that does dynamic range limiting in `PlotDataItem` (see #1140):

If all data is far above (or below) the screen, then it will all be clipped to the same value.
If auto-range is active, it will then center the view on the constant-valued clipped data, and set the view height to the minimum allowed.

Data will then be re-clipped according to the updated view, but since the view height is very small, the data will be clipped aggressively again. For far-away data, all clipped values will again be identical.

This process then repeats, with the center of the view range shifting towards the true data by approximately 1E6 every loop.
If the input data is all >1E10, this process takes an amusingly long time.

The solution is simple:
Never clip data when it is all off to the top or bottom, which we can judge from pre-existing information.
Then auto-range will jump to the proper range in one step, as intended. 
This also happens to be an optimization, since it saves calculation when nothing is visible.

The PR also switches `np.clip()` for `np.umath.clip()` throughout PlotDataItem.
This works around a problem with code overhead in numpy's main clip function, as discussed in  #1632 .

### CODE REVIEW

**Comment by j9ac9k** [comment]
In the comments, I would actually just put the full link to the issue (this has been _super_ helpful when seein gworkarounds for old Qt bugs that I periodically see, and then check out to see if the issue was resolved).

Link in this case is: https://github.com/numpy/numpy/issues/14281

**Comment by pijyoi** [comment]
I have created a ```pg.clip_array``` function in #1641.
@NilsNemitz , ```np.core.umath.clip``` does not perform well on macOS and Windows. If you want, you could merge ```pg.clip_array``` into your PR and I will drop #1641.

**Comment by NilsNemitz** [comment]
@pijyoi , that sounds good, it makes sense to have the workaround defined in only one place.
Could you check that your function leaves the input array intact? 
I need the "copy and clip only the copy" functionality of the normal np.clip without `out=` keyword.

**Comment by j9ac9k** [comment]
Now that #1641 is merged, feel free to make use of `pg.functions.clip_array`

**Comment by NilsNemitz** [comment]
Thank you @j9ac9k for handling this so quickly!
@pijyoi, since #1641 is already in, this now uses the new `functions.clip_array()` code.
Any other suggestions?

**Comment by j9ac9k** [comment]
This LGTM, thanks for submitting this @NilsNemitz Merging.

**Pull request merged**
