### PR TITLE
QVector3D conversion problem in GLViewWidget.py

### PR DESCRIPTION
**Pull request by 3DAlgoLab**
I fixed an error in GLViewWidget.py
This error happened when I changed the rotation mode from Euler to Quartenion. 
I found that the cause of the error is the wrong conversion of QVector3D to numpy.

### CODE REVIEW

**Comment by j9ac9k** [comment]
Hi @diem389 thanks for the PR!

Couple of requested changes.

1. Can you remove the commented out line of code
2. Can you replace the use of `np.array((cam[0], cam[1], cam[2]))` with `np.array((cam.x(), cam.y(), cam.z())`, or (and I'm not sure this would work, `np.array(*cam)`)

Is this meant to address #1780?  If so probably should put that in the body of the post (so the issue is closed when merged).

Thanks!

**Comment by j9ac9k** [comment]
Looks like you accidentally added a .vscode/settings.json file to the PR

**Comment by j9ac9k** [comment]
LGTM, going to let the CI chew on it; and then merge.

**Comment by 3DAlgoLab** [comment]
Sorry for confusion and troubles, I had to have more displine in how to contribute here. @j9ac9k Can I ask what is CI?

**Comment by j9ac9k** [comment]
CI is continuous integration, it's an automated test suite that runs on pull requests; in this web browser window, the CI is represented by the "checks" section, green checkmark means the test suite passed for that configuration (we sometimes get intermittent failures on some tests).

We all get crossed up on git sometimes, don't sweat it.

**Comment by j9ac9k** [comment]
o, just re-reading this, just realized that it's feasible for `cam` to _already_ be a np.ndarray 🤦🏻 

Can you make one more modification (sorry to keep requesting changes).

```python
if isinstance(cam, QVector3D):
   cam = np.array((cam.x() cam.y(), cam.z())
cam = cam.reshape((1,) * (pos.ndim - 1) + (3,))
```

**Comment by 3DAlgoLab** [comment]
Oops, I am so poor novice in the github environment. I deleted the forked version of master one by my mistake.

**Comment by j9ac9k** [comment]
Ha, yeah, looks like you'll have to re-fork, re-branch and re-submit a PR, I can't reopen the PR as the source repository has been deleted..

**Pull request closed without merging**
