### PR TITLE
Remove old unused mains

### PR DESCRIPTION
**Pull request by Jaime02**
This main entry points are old and worked for testing purposes. These should be removed, they are no longer needed.

### CODE REVIEW

**Comment by Jaime02** [comment]
Why some matplotlib tests suddenly do not work?

**Comment by ksunden** [comment]
Test failures appear to be related to the release of pyside6:

https://pypi.org/project/PySide6

See matplotlib/matplotlib#24158

**Comment by j9ac9k** [comment]
Thanks @ksunden for pointing out the mpl failure, we should probably submit a separate PR that skips those tests with the right/wrong combination of matplotlib + qt bindings.  

@Jaime02 can you remove the now unused imports?  If you click on Files Changed, you will see the unused imports being highlighted.

**Comment by Jaime02** [comment]
@j9ac9k  Done! I forgot doing that 🤓

**Comment by Jaime02** [comment]
Hey @j9ac9k can you check this again please?

**Comment by j9ac9k** [comment]
Hi @Jaime02 I was on vacation, sorry for the delayed review.  This LGTM, merging.

**Pull request merged**
