### PR TITLE
Added left-click and right-clicked signals 

### PR DESCRIPTION
**Pull request by rlegnain**
Adding left-clicked and right-clicked signal to InfiniteLine Class

### CODE REVIEW

**Comment by lesauxvi** [comment]
ok for me, but just wondering : what is the purpose of this? Can you provide an example where it can be helpful?

What do you think @campagnola and @ericdill ?

**Comment by rlegnain** [comment]
For example:
** if we have more than one infiniteline (slidebar), we can use the left-click to select a infiniteline . Once a infiniteline is selected, the properties of this infiniteline (color, width, position, ect..)  will be enabled and the user can change these properties. 

** we can use the right-click  to show a menu which could contain (remove infiniteline, set infiniteline at zero crossing, change font properties, ect.).

I am using these example now in my project. and other people could have another usages.

**Comment by lesauxvi** [comment]
OK, that is clear now. I agree with you regarding the right click. It could be very interesting to add a contextual menu to edit the item. However, I'm more dubitative for the left click: for example, how will you handle the situation where two infinite lines are really close to each other but at different Z levels?

**Comment by rlegnain** [comment]
The case of two infinite lines are close to each other will not be an issue. if the user face this case, he can zoom-in and then select the inifinite line. Furthermore, we can use the label also to select the inifinite line. 

So, I expect this case will not be an issue. However, it is just a feature, and the user can use it or disable it.

**Comment by lesauxvi** [comment]
why not. That is ok for me. What do you think @ericdill  and @campagnola ?

**Comment by lesauxvi** [comment]
Any reason to refuse this PR @campagnola and @ericdill ?

**Comment by j9ac9k** [comment]
Closing/ReOpening to trigger new CI runs.

**Comment by j9ac9k** [comment]
Variety of test errors:

On Pyside based tests

```
pyqtgraph system info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vsts/work/1/s/pyqtgraph/__init__.py", line 207, in <module>
    from .graphicsItems.GraphicsLayout import * 
  File "/home/vsts/work/1/s/pyqtgraph/graphicsItems/GraphicsLayout.py", line 6, in <module>
    from .PlotItem import PlotItem
  File "/home/vsts/work/1/s/pyqtgraph/graphicsItems/PlotItem/__init__.py", line 1, in <module>
    from .PlotItem import PlotItem
  File "/home/vsts/work/1/s/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 13, in <module>
    from .. LabelItem import LabelItem
  File "/home/vsts/work/1/s/pyqtgraph/graphicsItems/LabelItem.py", line 10, in <module>
    class LabelItem(GraphicsWidget, GraphicsWidgetAnchor):
  File "/home/vsts/work/1/s/pyqtgraph/graphicsItems/LabelItem.py", line 23, in LabelItem
    sigLeftDoubleClicked = QtCore.pyqtSignal(object)
AttributeError: module 'PySide2.QtCore' has no attribute 'pyqtSignal'
```

On PyQt4/5 based tests

```
FAILED examples/test_examples.py::testExamples[ Plotting.py - PyQt5 ]
FAILED examples/test_examples.py::testExamples[ CLIexample.py - PyQt5 ]
FAILED examples/test_examples.py::testExamples[ crosshair.py - PyQt5 ]
FAILED examples/test_examples.py::testExamples[ dockarea.py - PyQt5 ]
FAILED examples/test_examples.py::testExamples[ ErrorBarItem.py - PyQt5 ]
FAILED examples/test_examples.py::testExamples[ GraphicsLayout.py - PyQt5 ]
FAILED examples/test_examples.py::testExamples[ histogram.py - PyQt5 ]
FAILED examples/test_examples.py::testExamples[ imageAnalysis.py - PyQt5 ]
FAILED examples/test_examples.py::testExamples[ Legend.py - PyQt5 ]
FAILED examples/test_examples.py::testExamples[ PlotWidget.py - PyQt5 ]
FAILED examples/test_examples.py::testExamples[ scrollingPlots.py - PyQt5 ]
FAILED examples/test_examples.py::testExamples[ Symbols.py - PyQt5 ]
FAILED examples/test_examples.py::testExamples[ text.py - PyQt5 ]
FAILED examples/test_examples.py::testExamples[ DateAxisItem.py - PyQt5 ]
FAILED examples/test_examples.py::testExamples[ ViewBoxFeatures.py - PyQt5 0]
FAILED examples/test_examples.py::testExamples[ ViewBoxFeatures.py - PyQt5 1]
FAILED pyqtgraph/exporters/tests/test_svg.py::test_plotscene - AttributeError...
FAILED pyqtgraph/graphicsItems/tests/test_PlotDataItem.py::test_fft - Attribu...
FAILED pyqtgraph/graphicsItems/tests/test_PlotDataItem.py::test_clear - Attri...
FAILED pyqtgraph/graphicsItems/tests/test_PlotDataItem.py::test_clear_in_step_mode
FAILED pyqtgraph/graphicsItems/tests/test_PlotDataItem.py::test_clipping - At...
FAILED pyqtgraph/tests/test_ref_cycles.py::test_PlotWidget - AttributeError: ...
```

Can view specifics here:
https://dev.azure.com/pyqtgraph/pyqtgraph/_build/results?buildId=817&view=logs&j=be45790f-478d-5b97-0ed6-68d9728e630a&t=d35d130b-e186-595e-f2d8-a65d77e48ae7

**Comment by lidstrom83** [comment]
We've elsewhere been emitting the event along with the click signals to enable the user to distinguish between click types. It might be better to stick with that approach here too.

**Comment by j9ac9k** [comment]
> We've elsewhere been emitting the event along with the click signals to enable the user to distinguish between click types. It might be better to stick with that approach here too.

Yeah, I think that's probably the right strategy here too.

**Pull request closed without merging**
