### PR TITLE
derivativePlots_cleanup

### PR DESCRIPTION
**Pull request by meganbkratz**
This is a cleaned up version of the derivative and phase map transforms that Paul wrote. The code isn't changed, but I cherry-picked his relevant commit into a new branch for easier merging.

### CODE REVIEW

**Comment by j9ac9k** [comment]
Thanks for the PR @meganbkratz sorry it's taken us so long to follow up.

I think this is a great feature to add to the library.  Only thing I think we should add is a blurb about this in the examples.  Not suggesting you implement that change, given the amount of time has gone by.

**Comment by j9ac9k** [comment]
Results can be seen here:

https://dev.azure.com/pyqtgraph/pyqtgraph/_build/results?buildId=966&view=ms.vss-test-web.build-test-results-tab&runId=26128&resultId=100101&paneView=debug

Looks like all Qt5 based pipelines have the following error:

```
>       c.derivativeCheck.toggled.connect(self.updateDerivativeMode)
E       AttributeError: 'Ui_Form' object has no attribute 'derivativeCheck'

```

Qt4 based pipelines are failing for `test_fft`

```
def test_fft():
        f = 20.
        x = np.linspace(0, 1, 1000)
        y = np.sin(2 * np.pi * f * x)
        pd = pg.PlotDataItem(x, y)
        pd.setFftMode(True)
        x, y = pd.getData()
        assert abs(x[np.argmax(y)] - f) < 0.03
    
        x = np.linspace(0, 1, 1001)
        y = np.sin(2 * np.pi * f * x)
        pd.setData(x, y)
        x, y = pd.getData()
        assert abs(x[np.argmax(y)]- f) < 0.03
    
        pd.setLogMode(True, False)
        x, y = pd.getData()
>       assert abs(x[np.argmax(y)] - np.log10(f)) < 0.01
E       AssertionError: assert 1.1868876089881486 < 0.01
E        +  where 1.1868876089881486 = abs((0.11414238667583258 - 1.3010299956639813))
E        +    where 1.3010299956639813 = <ufunc 'log10'>(20.0)
E        +      where <ufunc 'log10'> = np.log10

AssertionError: assert 1.1868876089881486 < 0.01 + where 1.1868876089881486 = abs((0.11414238667583258 - 1.3010299956639813)) + where 1.3010299956639813 = <ufunc 'log10'>(20.0) + where <ufunc 'log10'> = np.log10
```

**Comment by j9ac9k** [comment]
The CI pipeline for win/py2/pyside1 is crashing at different tests... I suspect there is a CI issue at play.

**Comment by meganbkratz** [comment]
Thank you for working on this! I don't have the capacity to help right now, but I appreciate it!

**Comment by j9ac9k** [comment]
Hi @meganbkratz 

I figure 3 years is past the statute of limitations for the original authors to make requested changes :)

Now that the test suite is passing, do you happen to have some code that was taking advantage of the feature you were implementing?  I only ask to verify that the changes work as intended (I can add an example to the library plots too if need-be).

**Comment by j9ac9k** [comment]
Finally managed to use this feature, I've never actually used the context menus in pyqtgraph before so it took me a while to get to it.  Things are working as expected, merging.

**Pull request merged**
