### PR TITLE
Implement GLGridItem color.

### LINKED ISSUE #283: GLGridItem ignores color argument
If I try to create a GLGridItem with a different color grid (like for gray grid on white background), it doesn't do anything with the color argument.  In the paint method, It appears the color is set with `glColor4f(1, 1, 1, .3)`.

### PR DESCRIPTION
**Pull request by ixjlyons**
Fixes #283

### CODE REVIEW

**Comment by ixjlyons** [comment]
I think #648 basically took care of this. This just adds a setter for color (which isn't very Pythonic but a lot of the codebase seems to be more PyQt style).

**Comment by solarjoe** [comment]
Please re-open. Your implementation is better than https://github.com/pyqtgraph/pyqtgraph/pull/648 as it uses `fn.glColor(color)` and supports many different formats.

**Comment by ixjlyons** [comment]
@solarjoe sorry, I tried rebasing this on top of current `develop` and force pushing but it didn't seem to work, most likely because I deleted my local `glgriditem-color` branch first to fix a screwup. Woops.

I'm pretty doubtful this would have been merged any time soon had it been re-opened anyway, especially being fairly old and down low on the PR pile. Feel free to take this merge-conflict-free patch and create a new PR: https://github.com/ixjlyons/pyqtgraph/commit/a70491d519bacde8380e1db03e9fd278748781a4

**Comment by ixjlyons** [comment]
@solarjoe update if interested: https://github.com/pyqtgraph/pyqtgraph/issues/283 has been merged

**Pull request closed without merging**
