### PR TITLE
Update Travis according to new xvfb syntax

### PR DESCRIPTION
**Pull request by 2xB**
Travis updated their syntax to start xvfb. This is further described here: https://benlimmer.com/2019/01/14/travis-ci-xvfb/

### CODE REVIEW

**Comment by 2xB** [comment]
Notice that Travis still fails, because pytest.ini includes `--faulthandler-timeout`, which is only available when using pytest-faulthandler. This also means that currently just using pytest on the repository leads to the exact same failure.

**Comment by ixjlyons** [comment]
We might as well go ahead and install pytest-faulthandler at the same time pytest-xdist and pytest-cov are installed right?

**Comment by j9ac9k** [comment]
Do we even want to maintain using travis?

**Comment by ixjlyons** [comment]
I don't see a strong reason to keep it. I haven't looked at the Azure pipelines stuff in detail -- are we doing all the same checks there that are being done on Travis currently? From comments in the config (not necessarily saying we should keep all of them):

```
    # Run unit tests
    # check line endings
    # Check repo size does not expand too much
    # Check for style issues
    # Check install works
    # Check double-install fails
    # Check we can import pg
```

The other thing I can think of is that we have Travis configured with a coverage service that integrates with Github to show coverage deltas in pull requests. I personally think that has value and we should be a bit better about adding tests for things as we fix them. Obviously we've been in the "get the current set of tests passing first" mode -- just looking forward a bit.

**Comment by j9ac9k** [comment]
When creating azure pipelines config, I used the unit-testing check as the basis of the pipeline, but didn't implement the linting checks and some of the other checks.  If we're seriously considering ditching travis; that would be a good thing to implement first.

That said, macOS on azure-pipelines is being problematic (with context to the viewbox mapping test); I'm not sure if that same error is persistent with travis or not (AFAIK our travis config just tests linux), but if not, we may want to use Travis just for macOS checks until we get Azure to behave as we intend.

**Comment by j9ac9k** [comment]
Thanks for the PR @2xB I'll merge this, given that we are currently using travis we should maintain it's configuration...the discussion on whether we should ditch travis altogether should likely not reside in this PR.

**Comment by 2xB** [comment]
* I like our Travis CI e.g. for the mentioned linting, the flake8 syntax checker and for the fact that it is trivially simple to get own forks of this repository using the same CI, also for the fact that it can simply be used to automate pypi deployment, if one wants to. And for the fact that it currently supports OpenGL ^^
 * No further package (such as pytest-faulthandler) should in my opinion be needed to run pytest on this project on ones own PC - if that is disagreed with, it should at least be documented in the README.

**Comment by j9ac9k** [comment]
You can setup azure pipelines on your own fork easily enough, I have azure pipelines running on my fork... I think it's the same level of difficulty as setting up travis.

[Azure pipelines also supports automated pypi deployment](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?view=azure-devops&tabs=yaml)

In terms of the lint checker, we just don't do that in azure pipelines as my goal was to get unit-testing up, we can (and should) add lint-checking to the pipeline build, but we should likely only do that check on 1 of our 18 pipelines (although after we release 0.11, I'm likely going to push to deprecate anything Qt < 5.9 and python < 3.5, so our number of pipelines will decrease).

I can see OpenGL support being a reason to keep using Travis, especially if implementing OpenGL support on macOS/Windows on Azure pipelines becomes problematic.

Regarding test requirements/processes, they're [spelled out in `CONTRIBUTING.md`](https://github.com/pyqtgraph/pyqtgraph/blob/develop/CONTRIBUTING.md#testing-setting-up-a-test-environment).  No pytest plugins are _required_ to test (considering proposing future versions to use pytest-qt, but we're not there yet); but I highly recommend using tox/tox-conda so you can test on a variety of qt-bindings with ease.

**Comment by 2xB** [comment]
Well, it seems I my opinion is mainly based on me having most of my experience with Travis...

For the requirements, pytest-faulthandler is at the moment required to test, that's what I try to say. See e.g. [the last Travis build on `develop`](https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/548847482), line 643.

**Comment by j9ac9k** [comment]
> Well, it seems like my opinion is mainly based on me having most of my experience with Travis...
> 
> For the requirements, pytest-faulthandler is at the moment required to test, that's what I try to say. See e.g. [the last Travis build on `develop`](https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/548847482), line 643.

My reluctance w/ travis is their post buy-out engineer layoff a few months ago: https://twitter.com/ReinH/status/1098663375985229825

In terms of feature-set, azure-pipelines does offer more parallel jobs, and conda-forge migrated over right away due to speed related issues with what appears to be pretty good success.

Regarding pytest-faulthanlder, the error you site on travis is indeed what happens when you run pytest with-out pytest-faulthandler as you rightly identified, it's [due to this line right here](https://github.com/pyqtgraph/pyqtgraph/blob/5238c097d59fd57f7e819484ce0ba80af4fc7972/pytest.ini#L6).  To my knowledge, pytest-faulthandler has no other way to set its options; so I'm thinking we should make that argument be explicit when calling pytest within CI systems (so otherwise you don't need it to install it).

**Comment by 2xB** [comment]
This is new to me and very sad.

For pytest-faulthandler, I created a feature request to fix this: https://github.com/pytest-dev/pytest-faulthandler/issues/34. As you already got a very fast response on that repository, this might be the easiest solution with which also others can profit for their projects.

**Pull request merged**
