### PR TITLE
Improve Performance of pg.Point methods

### PR DESCRIPTION
**Pull request by j9ac9k**
While working on #1724 I noticed the `pg.Point` methods weren't making good use of the QPointF superclass methods at its disposal.  I decided I would modify that within Point itself, and modify calls to point object to use the modified methods.  I also deprecated some methods in favor of equivalent methods implemented with QPointF.

### CODE REVIEW

**Comment by pijyoi** [comment]
Manhattan length is defined as abs(x) + abs(y), not the same as hypot(x, y) = sqrt(x*x + y*y)

**Comment by pijyoi** [comment]
The definition of angle() for Point is non-conventional. We would expect ```p1.angle(p2)``` to mean the angle from p1 to p2.
```python
In [2]: p1 = pg.Point(1, 0)
In [3]: p2 = pg.Point(0, 1)
In [4]: p1.angle(p2)
Out[4]: -90.0
In [6]: v1 = pg.Vector(1, 0)
In [7]: v2 = pg.Vector(0, 1)
In [8]: v1.angle(v2)
Out[8]: 90.0
```

**Comment by j9ac9k** [comment]
> Manhattan length is defined as abs(x) + abs(y), not the same as hypot(x, y) = sqrt(x_x + y_y)

Well, that's embarrassing 😆

**Comment by j9ac9k** [comment]
umm... I screwed something up git wise, and clearly didn't think this out right to begin with, going to close this PR work on what the implementation should look like and resubmit.

**Pull request closed without merging**
