### PR TITLE
Trying to add support for roiCurves with multi-color image stacks in ImageView

### PR DESCRIPTION
**Pull request by ptweir**
roiCurve is replaced by a list, roiCurves. When an roi is changed in a 4-dimensional image stack, an roiCurve is added for each color.

*I apologize in advance if these changes are undesirable. (This is my first time submitting a pull request on an open source project.)

### CODE REVIEW

**Comment by ericdill** [comment]
Thanks for the PR @ptweir !  Could you add an example in https://github.com/pyqtgraph/pyqtgraph/tree/develop/examples that demonstrates this usage? Seeing it in action would help evaluate the PR

**Comment by ptweir** [comment]
Hi @ericdill thanks for the suggestion. Let me know how to improve the example and/or changes.

**Comment by ixjlyons** [comment]
It turns out `ImageView` has sort of independently evolved to support ROI average curves for each color channel, including stacked color images, so this example just works (once #1291 is merged). Making a note here that we should cherry-pick f5c4eee0c6d80f657dfc534fcdc0a635fedd9941 because that's a pretty cool example that really demonstrates what's going on.

**Comment by j9ac9k** [comment]
@ixjlyons just saw your comment (why am I so bad at this); you suggesting either updating this PR (or creating a new PR) with just  https://github.com/pyqtgraph/pyqtgraph/commit/f5c4eee0c6d80f657dfc534fcdc0a635fedd9941  and things will "just work"?

@ptweir sorry this PR has sat idle for so long, we've had quite the PR back-log which I've made a priority to go through.

**Comment by ixjlyons** [comment]
@j9ac9k yeah the example works with the current state of `ImageView` without further modification. My suggestion was to just grab this example script then add it to the example app. I started doing it and waffled on it because I'm not sure it makes sense to have both `examples/ImageView.py` and this one. Maybe they should just be merged.

**Comment by outofculture** [comment]
I took @ixjlyons' thought and ran with it; this has a funner example than the original, so I say we just go with this one. I'm closing this so I can just merge that.

**Pull request closed without merging**
