### PR TITLE
ScatterPlotItem: implement hidpi pixmap

### PR DESCRIPTION
**Pull request by pijyoi**
This PR came about while investigating #2854.
Although a workaround for #2854 was to disable `useCache`, the true reason for the blurriness on hidpi displays is due to the pixmap atlas only being rendered at a dpi of 1.0.

1) The improved sharpness of this PR vs master (on a hidpi display) can be seen from the `ScatterPlot.py`, `Symbol.py` examples.
2) On a hidpi display, this PR achieves a higher frame-rate than master on `ScatterPlotSpeedTest.py`. i.e. there is a drawing penalty when a lo-res pixmap needs to be scaled to be painted onto a hidpi display.

### CODE REVIEW

**Comment by j9ac9k** [comment]
I think you can programatically get that ratio you need by doing the following inside the paint method

```python
dpi = self.getViewWidget().metric(QtGui.QPaintDevice.PaintDeviceMetric.PdmPhysicalDpiX)
pixmap_dpi = self.fragmentAtlas.pixmap.metric(QtGui.QPaintDevice.PaintDeviceMetric.PdmPhysicalDpiX)

scale = dpi / pixmap_dpi
```

Likely don't want to be calling this during every paint call...

**Comment by pijyoi** [comment]
>I think you can programatically get that ratio you need by doing the following inside the paint method
>dpi = self.getViewWidget().metric(QtGui.QPaintDevice.PaintDeviceMetric.PdmPhysicalDpiX)
pixmap_dpi = self.fragmentAtlas.pixmap.metric(QtGui.QPaintDevice.PaintDeviceMetric.PdmPhysicalDpiX)
>scale = dpi / pixmap_dpi

Although we call it "hi-dpi", the quantity that we are interested in is the DPR rather than the DPI.

**Comment by pijyoi** [comment]
As a bonus, this PR also fixes the following artifacts that appear for the bottom right plot of `ScatterPlot.py` example the moment the mouse is moved over it.
(Windows 10 device pixel ratio 1.25, PySide6 6.6.0)
before_br

**Comment by j9ac9k** [comment]
Thanks @pijyoi for the PR, this LGTM merging!

**Pull request merged**
