### PR TITLE
[WIP] Fix pg.exit test in case pyqtgraph is not installed

### PR DESCRIPTION
**Pull request by ixjlyons**
Stole the implementation from the other test in `test_exit_crash.py` even though it's skipped. This test should now work on Travis where we don't install pyqtgraph until after the tests are run.

### CODE REVIEW

**Comment by ixjlyons** [comment]
Alright this isn't working at all. If anyone has an idea, let me know :sweat_smile:

**Comment by j9ac9k** [comment]
I think I got it on my PR here https://github.com/pyqtgraph/pyqtgraph/pull/962 . Feel free to glance over the code changes, but there are two main factors.

1. We actually install the pyqtgraph lib
2. We do not pass `shell=True` to `subprocesss.Popen()`

I'm not sure if `close_fds=True` is necessary or not; I added it in because 🤷‍♂

**Comment by ixjlyons** [comment]
It's not really important, but just to check my understanding I verified you don't need the insert pyqtgraph's root dir into the path if pyqtgraph is installed before running the tests. I guess we don't really want the test code to be making lots of assumptions about how CI is set up, but I think assuming you can import pyqtgraph in a subprocess is reasonable.

@j9ac9k Going to close this since you made a couple other changes to the travis config in the other PR.

**Comment by j9ac9k** [comment]
Sounds good; I think there were a few minor tweaks I wanted to make; will get that merged later today.

**Pull request closed without merging**
