### PR TITLE
Update functions.py

### PR DESCRIPTION
**Pull request by DavidLP**
BUG: fix scaling with numpy 1.10

### CODE REVIEW

**Comment by lidstrom83** [comment]
I've verified the bug (by running the ImageItem example with numpy 1.10 installed).  This fix works for me.

Not sure why Travis fails though.

**Comment by ericdill** [comment]
Travis is failing due to an exception raised by the coverage library. While I am unclear why this exception is being raised, it is definitely safe to ignore

**Comment by mivade** [comment]
Thanks for this. Just to add for cross-referencing, this addresses bug #243.

**Comment by campagnola** [comment]
An in-place multiply should be faster and use less memory. There's a good discussion of the numpy changes that led to the bug and a suggested workaround here:
https://mail.scipy.org/pipermail/numpy-discussion/2012-September/063926.html

**Pull request closed without merging**
