### PR TITLE
flowchart: python3: replaced calls to unicode function with asUnicode

### PR DESCRIPTION
**Pull request by giantamoeba**
necessary for running flowcharts on python3

### CODE REVIEW

**Comment by QuLogic** [comment]
The functional parts look mostly the same as #423, though the whitespace cleanup is different.

**Comment by sscherfke** [comment]
Can this PR or #423 please be merged?

**Comment by sscherfke** [comment]
Any updates on this?

**Comment by j9ac9k** [comment]
Implemented with #886

**Pull request closed without merging**
