### PR TITLE
remote legacy work-around for old numpy errors

### PR DESCRIPTION
**Pull request by danielhrisca**
The referenced numpy bug had been fixed since 2013 (https://github.com/numpy/numpy/issues/2084)

### CODE REVIEW

**Comment by j9ac9k** [comment]
Can we establish a minimum numpy version in `setup.py`?

**Comment by danielhrisca** [comment]
I think it is safe to assume that starting with 1.8.0 the issue was fixed (https://pypi.org/project/numpy/1.8.0/)

**Comment by j9ac9k** [comment]
LGTM can't view CI stuff on mobile, will merge when I hop on my laptop (unless someone beats me to it)
Thanks for the PR!

**Comment by j9ac9k** [comment]
Merging, thanks again for the PR @danielhrisca

**Comment by danielhrisca** [comment]
I'm glad to help and I'm looking forward to the 0.11.0 release

**Pull request merged**
