### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by bilderbuchi**
Ping @j9ac9k ;-)

### CODE REVIEW

**Comment by j9ac9k** [comment]
gonna have to wait to see what the CI says for a diff this large 😆

**Comment by bilderbuchi** [comment]
Let's hope there are no flaky tests in your test suite :D

**Comment by j9ac9k** [comment]
> Let's hope there are no flaky tests in your test suite :D

oh we have no shortage of those unfortunately ...luckily I remember which ones they are.

**Comment by j9ac9k** [comment]
thanks for the PR @bilderbuchi merging

**Pull request merged**
