### PR TITLE
Fix tox config, bump min numpy to 1.22

### PR DESCRIPTION
**Pull request by j9ac9k**
PR addresses 3 issues

- Fix `tox.ini` to run only on compatible configurations
- Remove usage of `numpy.product` which is deprecated as of NumPy 1.25 and will be removed in NumPy 2.0
- Bump minimum NumPy from 1.21 to 1.22 per NEP-29 timeline

### CODE REVIEW

**Comment by j9ac9k** [comment]
Computer says no...

**Comment by j9ac9k** [comment]
I can replicate the locally, only occurs on numpy 1.22.x, not 1.23.x.

**Comment by pijyoi** [comment]
This workaround for `np.clip` on Windows (or rather MSVC) can also be removed.
https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/functions.py#L1215-L1219

**Comment by pijyoi** [comment]
Maybe add this link as a comment https://github.com/numpy/numpy/issues/21612

**Pull request merged**
