### PR TITLE
ImageExporter py2-pyside fix with test

### PR DESCRIPTION
**Pull request by ixjlyons**
Adds a test on top of #1133. It pretty much only hits the code that #1133 fixes, but it's better than nothing. We should really have more coverage of `ImageExporter` - maybe for a future PR?

### CODE REVIEW

**Comment by j9ac9k** [comment]
hmm...that was a weird CI failure, going to rerun that one failed test...if it's good, I'll merge

**Comment by j9ac9k** [comment]
still failing, re-running CI on an unrelated PR and see if I get the same failure....

**Comment by j9ac9k** [comment]
rerunning CI on just the dev branch to see if unrelated.... can follow along here:

https://dev.azure.com/pyqtgraph/pyqtgraph/_build/results?buildId=660&view=results

**Comment by ixjlyons** [comment]
Just a blind guess, but I didn't explicitly instantiate a `QApplication` instance at the module level though other test modules seem to do so.

**Comment by j9ac9k** [comment]
oh, that's probably it!  Mind adding that into the test? ...not sure if this is a Qt 5.9 issue, a macOS issue or a python 3.6 issue.... (or all 3).

**Comment by j9ac9k** [comment]
I ran the CI on the develop branch as it stands today, and it doesn't have this issue, so this error is definitely a result of a change in this PR.

**Comment by ixjlyons** [comment]
Done. The funny thing is I originally had it in there but removed it because it didn't seem necessary :sweat_smile: Hopefully that's it

**Comment by j9ac9k** [comment]
It passed! Merging!

**Pull request merged**
