### PR TITLE
fix legendItem drag

### PR DESCRIPTION
**Pull request by ombschervister**
Fix https://github.com/pyqtgraph/pyqtgraph/issues/332

### CODE REVIEW

**Comment by ombschervister** [comment]
Can you explain what does it mean "Merging #333 into develop will decrease coverage by -<.01%"?

**Comment by ombschervister** [comment]
1. Ev.accept() in mouseDragEvent fix problem, but i do not understand what behavior must be for ev.ignore. I think after ev.ignore mouseDrag must stop calling, but now it is not.

2. If I delete lines about hoverEvent from mousePressEvent, problem fix too.
       Deleted lines:
           if self.lastHoverEvent is not None:
               # If the mouse has moved since the last hover event, send a new one.
               # This can happen if a context menu is open while the mouse is moving.
               if ev.scenePos() != self.lastHoverEvent.scenePos():
                   self.sendHoverEvents(ev)

**Comment by lesauxvi** [comment]
look at my remark at #332 ...

**Comment by j9ac9k** [comment]
Thanks for the PR, sorry it took us so long to follow up.   It looks good to me, will be merging!.

**Pull request merged**
